// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gsdirectory.proto

package stream

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// GS -> Directory 命令号
type GSDirectoryCmdID int32

const (
	GSDirectoryCmdID_InValidGSCmd     GSDirectoryCmdID = 0
	GSDirectoryCmdID_GSLoginCmd       GSDirectoryCmdID = 3001
	GSDirectoryCmdID_GSHeartbeatCmd   GSDirectoryCmdID = 3003
	GSDirectoryCmdID_GSLogoutCmd      GSDirectoryCmdID = 3005
	GSDirectoryCmdID_GSCreateRoomCmd  GSDirectoryCmdID = 4001
	GSDirectoryCmdID_GSTouchRoomCmd   GSDirectoryCmdID = 4003
	GSDirectoryCmdID_GSDestroyRoomCmd GSDirectoryCmdID = 4005
)

var GSDirectoryCmdID_name = map[int32]string{
	0:    "InValidGSCmd",
	3001: "GSLoginCmd",
	3003: "GSHeartbeatCmd",
	3005: "GSLogoutCmd",
	4001: "GSCreateRoomCmd",
	4003: "GSTouchRoomCmd",
	4005: "GSDestroyRoomCmd",
}

var GSDirectoryCmdID_value = map[string]int32{
	"InValidGSCmd":     0,
	"GSLoginCmd":       3001,
	"GSHeartbeatCmd":   3003,
	"GSLogoutCmd":      3005,
	"GSCreateRoomCmd":  4001,
	"GSTouchRoomCmd":   4003,
	"GSDestroyRoomCmd": 4005,
}

func (x GSDirectoryCmdID) String() string {
	return proto.EnumName(GSDirectoryCmdID_name, int32(x))
}

func (GSDirectoryCmdID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{0}
}

// 房间创建途径
type CreateFlag int32

const (
	CreateFlag_CreateRoomUnknown CreateFlag = 0
	CreateFlag_CreateRoomSystem  CreateFlag = 1
	CreateFlag_CreateRoomPlayer  CreateFlag = 2
	CreateFlag_CreateRoomGS      CreateFlag = 3
)

var CreateFlag_name = map[int32]string{
	0: "CreateRoomUnknown",
	1: "CreateRoomSystem",
	2: "CreateRoomPlayer",
	3: "CreateRoomGS",
}

var CreateFlag_value = map[string]int32{
	"CreateRoomUnknown": 0,
	"CreateRoomSystem":  1,
	"CreateRoomPlayer":  2,
	"CreateRoomGS":      3,
}

func (x CreateFlag) String() string {
	return proto.EnumName(CreateFlag_name, int32(x))
}

func (CreateFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{1}
}

//
//GS主动向Directory注册:
//GSLogin(gameID, svcName, podName, host, port) -> (status)
type GSLogin struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	SvcName              string   `protobuf:"bytes,2,opt,name=svcName,proto3" json:"svcName,omitempty"`
	PodName              string   `protobuf:"bytes,3,opt,name=podName,proto3" json:"podName,omitempty"`
	Host                 string   `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSLogin) Reset()         { *m = GSLogin{} }
func (m *GSLogin) String() string { return proto.CompactTextString(m) }
func (*GSLogin) ProtoMessage()    {}
func (*GSLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{0}
}

func (m *GSLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSLogin.Unmarshal(m, b)
}
func (m *GSLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSLogin.Marshal(b, m, deterministic)
}
func (m *GSLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSLogin.Merge(m, src)
}
func (m *GSLogin) XXX_Size() int {
	return xxx_messageInfo_GSLogin.Size(m)
}
func (m *GSLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_GSLogin.DiscardUnknown(m)
}

var xxx_messageInfo_GSLogin proto.InternalMessageInfo

func (m *GSLogin) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *GSLogin) GetSvcName() string {
	if m != nil {
		return m.SvcName
	}
	return ""
}

func (m *GSLogin) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *GSLogin) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *GSLogin) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GSLoginAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSLoginAck) Reset()         { *m = GSLoginAck{} }
func (m *GSLoginAck) String() string { return proto.CompactTextString(m) }
func (*GSLoginAck) ProtoMessage()    {}
func (*GSLoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{1}
}

func (m *GSLoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSLoginAck.Unmarshal(m, b)
}
func (m *GSLoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSLoginAck.Marshal(b, m, deterministic)
}
func (m *GSLoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSLoginAck.Merge(m, src)
}
func (m *GSLoginAck) XXX_Size() int {
	return xxx_messageInfo_GSLoginAck.Size(m)
}
func (m *GSLoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GSLoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_GSLoginAck proto.InternalMessageInfo

func (m *GSLoginAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//
//GS主动向Directory心跳 load 是一个（0，100）值，用来衡量当前GS负载情况:
//GSHeartbeat(load) -> (status)
type GSHeartbeat struct {
	Load                 uint32   `protobuf:"varint,1,opt,name=load,proto3" json:"load,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSHeartbeat) Reset()         { *m = GSHeartbeat{} }
func (m *GSHeartbeat) String() string { return proto.CompactTextString(m) }
func (*GSHeartbeat) ProtoMessage()    {}
func (*GSHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{2}
}

func (m *GSHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSHeartbeat.Unmarshal(m, b)
}
func (m *GSHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSHeartbeat.Marshal(b, m, deterministic)
}
func (m *GSHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSHeartbeat.Merge(m, src)
}
func (m *GSHeartbeat) XXX_Size() int {
	return xxx_messageInfo_GSHeartbeat.Size(m)
}
func (m *GSHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_GSHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_GSHeartbeat proto.InternalMessageInfo

func (m *GSHeartbeat) GetLoad() uint32 {
	if m != nil {
		return m.Load
	}
	return 0
}

type GSHeartbeatAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSHeartbeatAck) Reset()         { *m = GSHeartbeatAck{} }
func (m *GSHeartbeatAck) String() string { return proto.CompactTextString(m) }
func (*GSHeartbeatAck) ProtoMessage()    {}
func (*GSHeartbeatAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{3}
}

func (m *GSHeartbeatAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSHeartbeatAck.Unmarshal(m, b)
}
func (m *GSHeartbeatAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSHeartbeatAck.Marshal(b, m, deterministic)
}
func (m *GSHeartbeatAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSHeartbeatAck.Merge(m, src)
}
func (m *GSHeartbeatAck) XXX_Size() int {
	return xxx_messageInfo_GSHeartbeatAck.Size(m)
}
func (m *GSHeartbeatAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GSHeartbeatAck.DiscardUnknown(m)
}

var xxx_messageInfo_GSHeartbeatAck proto.InternalMessageInfo

func (m *GSHeartbeatAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//
//GS主动向Directory心跳:
//GSLogout(gameID, svcName, podName) -> (status)
type GSLogout struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	SvcName              string   `protobuf:"bytes,2,opt,name=svcName,proto3" json:"svcName,omitempty"`
	PodName              string   `protobuf:"bytes,3,opt,name=podName,proto3" json:"podName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSLogout) Reset()         { *m = GSLogout{} }
func (m *GSLogout) String() string { return proto.CompactTextString(m) }
func (*GSLogout) ProtoMessage()    {}
func (*GSLogout) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{4}
}

func (m *GSLogout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSLogout.Unmarshal(m, b)
}
func (m *GSLogout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSLogout.Marshal(b, m, deterministic)
}
func (m *GSLogout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSLogout.Merge(m, src)
}
func (m *GSLogout) XXX_Size() int {
	return xxx_messageInfo_GSLogout.Size(m)
}
func (m *GSLogout) XXX_DiscardUnknown() {
	xxx_messageInfo_GSLogout.DiscardUnknown(m)
}

var xxx_messageInfo_GSLogout proto.InternalMessageInfo

func (m *GSLogout) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *GSLogout) GetSvcName() string {
	if m != nil {
		return m.SvcName
	}
	return ""
}

func (m *GSLogout) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

type GSLogoutAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSLogoutAck) Reset()         { *m = GSLogoutAck{} }
func (m *GSLogoutAck) String() string { return proto.CompactTextString(m) }
func (*GSLogoutAck) ProtoMessage()    {}
func (*GSLogoutAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{5}
}

func (m *GSLogoutAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSLogoutAck.Unmarshal(m, b)
}
func (m *GSLogoutAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSLogoutAck.Marshal(b, m, deterministic)
}
func (m *GSLogoutAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSLogoutAck.Merge(m, src)
}
func (m *GSLogoutAck) XXX_Size() int {
	return xxx_messageInfo_GSLogoutAck.Size(m)
}
func (m *GSLogoutAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GSLogoutAck.DiscardUnknown(m)
}

var xxx_messageInfo_GSLogoutAck proto.InternalMessageInfo

func (m *GSLogoutAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 房间信息
type RoomInfo struct {
	RoomID               uint64    `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	RoomName             string    `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	MaxPlayer            uint32    `protobuf:"varint,3,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	Mode                 int32     `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	CanWatch             int32     `protobuf:"varint,5,opt,name=canWatch,proto3" json:"canWatch,omitempty"`
	Visibility           int32     `protobuf:"varint,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	RoomProperty         []byte    `protobuf:"bytes,7,opt,name=roomProperty,proto3" json:"roomProperty,omitempty"`
	Owner                uint32    `protobuf:"varint,8,opt,name=owner,proto3" json:"owner,omitempty"`
	State                RoomState `protobuf:"varint,9,opt,name=state,proto3,enum=stream.RoomState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{6}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RoomInfo) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *RoomInfo) GetMaxPlayer() uint32 {
	if m != nil {
		return m.MaxPlayer
	}
	return 0
}

func (m *RoomInfo) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *RoomInfo) GetCanWatch() int32 {
	if m != nil {
		return m.CanWatch
	}
	return 0
}

func (m *RoomInfo) GetVisibility() int32 {
	if m != nil {
		return m.Visibility
	}
	return 0
}

func (m *RoomInfo) GetRoomProperty() []byte {
	if m != nil {
		return m.RoomProperty
	}
	return nil
}

func (m *RoomInfo) GetOwner() uint32 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *RoomInfo) GetState() RoomState {
	if m != nil {
		return m.State
	}
	return RoomState_RoomStateNil
}

//
//GS主动创建房间:
//CreateRoom(svcName, podName, gameID, roomInfo, ttl) -> (status, roomID)
type CreateRoom struct {
	SvcName              string        `protobuf:"bytes,1,opt,name=svcName,proto3" json:"svcName,omitempty"`
	PodName              string        `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	GameID               uint32        `protobuf:"varint,3,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomInfo             *RoomInfo     `protobuf:"bytes,4,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	Ttl                  uint32        `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	WatchSetting         *WatchSetting `protobuf:"bytes,6,opt,name=watchSetting,proto3" json:"watchSetting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateRoom) Reset()         { *m = CreateRoom{} }
func (m *CreateRoom) String() string { return proto.CompactTextString(m) }
func (*CreateRoom) ProtoMessage()    {}
func (*CreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{7}
}

func (m *CreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoom.Unmarshal(m, b)
}
func (m *CreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoom.Marshal(b, m, deterministic)
}
func (m *CreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoom.Merge(m, src)
}
func (m *CreateRoom) XXX_Size() int {
	return xxx_messageInfo_CreateRoom.Size(m)
}
func (m *CreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoom proto.InternalMessageInfo

func (m *CreateRoom) GetSvcName() string {
	if m != nil {
		return m.SvcName
	}
	return ""
}

func (m *CreateRoom) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *CreateRoom) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *CreateRoom) GetRoomInfo() *RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

func (m *CreateRoom) GetTtl() uint32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *CreateRoom) GetWatchSetting() *WatchSetting {
	if m != nil {
		return m.WatchSetting
	}
	return nil
}

type CreateRoomAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomAck) Reset()         { *m = CreateRoomAck{} }
func (m *CreateRoomAck) String() string { return proto.CompactTextString(m) }
func (*CreateRoomAck) ProtoMessage()    {}
func (*CreateRoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{8}
}

func (m *CreateRoomAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomAck.Unmarshal(m, b)
}
func (m *CreateRoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomAck.Marshal(b, m, deterministic)
}
func (m *CreateRoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomAck.Merge(m, src)
}
func (m *CreateRoomAck) XXX_Size() int {
	return xxx_messageInfo_CreateRoomAck.Size(m)
}
func (m *CreateRoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomAck proto.InternalMessageInfo

func (m *CreateRoomAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateRoomAck) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

//
//GS重置房间TTL:
//TouchRoom(gameID, roomID, ttl) -> (status)
type TouchRoom struct {
	SvcName              string   `protobuf:"bytes,1,opt,name=svcName,proto3" json:"svcName,omitempty"`
	PodName              string   `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	GameID               uint32   `protobuf:"varint,3,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,4,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Ttl                  uint32   `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchRoom) Reset()         { *m = TouchRoom{} }
func (m *TouchRoom) String() string { return proto.CompactTextString(m) }
func (*TouchRoom) ProtoMessage()    {}
func (*TouchRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{9}
}

func (m *TouchRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchRoom.Unmarshal(m, b)
}
func (m *TouchRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchRoom.Marshal(b, m, deterministic)
}
func (m *TouchRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchRoom.Merge(m, src)
}
func (m *TouchRoom) XXX_Size() int {
	return xxx_messageInfo_TouchRoom.Size(m)
}
func (m *TouchRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchRoom.DiscardUnknown(m)
}

var xxx_messageInfo_TouchRoom proto.InternalMessageInfo

func (m *TouchRoom) GetSvcName() string {
	if m != nil {
		return m.SvcName
	}
	return ""
}

func (m *TouchRoom) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *TouchRoom) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *TouchRoom) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *TouchRoom) GetTtl() uint32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type TouchRoomAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchRoomAck) Reset()         { *m = TouchRoomAck{} }
func (m *TouchRoomAck) String() string { return proto.CompactTextString(m) }
func (*TouchRoomAck) ProtoMessage()    {}
func (*TouchRoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{10}
}

func (m *TouchRoomAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchRoomAck.Unmarshal(m, b)
}
func (m *TouchRoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchRoomAck.Marshal(b, m, deterministic)
}
func (m *TouchRoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchRoomAck.Merge(m, src)
}
func (m *TouchRoomAck) XXX_Size() int {
	return xxx_messageInfo_TouchRoomAck.Size(m)
}
func (m *TouchRoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchRoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_TouchRoomAck proto.InternalMessageInfo

func (m *TouchRoomAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//
//GS主动销毁房间:
//DestroyRoom(svcName, podName, gameID, roomID) -> (status)
type DestroyRoom struct {
	SvcName              string   `protobuf:"bytes,1,opt,name=svcName,proto3" json:"svcName,omitempty"`
	PodName              string   `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	GameID               uint32   `protobuf:"varint,3,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,4,opt,name=roomID,proto3" json:"roomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyRoom) Reset()         { *m = DestroyRoom{} }
func (m *DestroyRoom) String() string { return proto.CompactTextString(m) }
func (*DestroyRoom) ProtoMessage()    {}
func (*DestroyRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{11}
}

func (m *DestroyRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyRoom.Unmarshal(m, b)
}
func (m *DestroyRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyRoom.Marshal(b, m, deterministic)
}
func (m *DestroyRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyRoom.Merge(m, src)
}
func (m *DestroyRoom) XXX_Size() int {
	return xxx_messageInfo_DestroyRoom.Size(m)
}
func (m *DestroyRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyRoom.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyRoom proto.InternalMessageInfo

func (m *DestroyRoom) GetSvcName() string {
	if m != nil {
		return m.SvcName
	}
	return ""
}

func (m *DestroyRoom) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *DestroyRoom) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *DestroyRoom) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type DestroyRoomAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyRoomAck) Reset()         { *m = DestroyRoomAck{} }
func (m *DestroyRoomAck) String() string { return proto.CompactTextString(m) }
func (*DestroyRoomAck) ProtoMessage()    {}
func (*DestroyRoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17fe7d4803e74ca, []int{12}
}

func (m *DestroyRoomAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyRoomAck.Unmarshal(m, b)
}
func (m *DestroyRoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyRoomAck.Marshal(b, m, deterministic)
}
func (m *DestroyRoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyRoomAck.Merge(m, src)
}
func (m *DestroyRoomAck) XXX_Size() int {
	return xxx_messageInfo_DestroyRoomAck.Size(m)
}
func (m *DestroyRoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyRoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyRoomAck proto.InternalMessageInfo

func (m *DestroyRoomAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterEnum("stream.GSDirectoryCmdID", GSDirectoryCmdID_name, GSDirectoryCmdID_value)
	proto.RegisterEnum("stream.CreateFlag", CreateFlag_name, CreateFlag_value)
	proto.RegisterType((*GSLogin)(nil), "stream.GSLogin")
	proto.RegisterType((*GSLoginAck)(nil), "stream.GSLoginAck")
	proto.RegisterType((*GSHeartbeat)(nil), "stream.GSHeartbeat")
	proto.RegisterType((*GSHeartbeatAck)(nil), "stream.GSHeartbeatAck")
	proto.RegisterType((*GSLogout)(nil), "stream.GSLogout")
	proto.RegisterType((*GSLogoutAck)(nil), "stream.GSLogoutAck")
	proto.RegisterType((*RoomInfo)(nil), "stream.RoomInfo")
	proto.RegisterType((*CreateRoom)(nil), "stream.CreateRoom")
	proto.RegisterType((*CreateRoomAck)(nil), "stream.CreateRoomAck")
	proto.RegisterType((*TouchRoom)(nil), "stream.TouchRoom")
	proto.RegisterType((*TouchRoomAck)(nil), "stream.TouchRoomAck")
	proto.RegisterType((*DestroyRoom)(nil), "stream.DestroyRoom")
	proto.RegisterType((*DestroyRoomAck)(nil), "stream.DestroyRoomAck")
}

func init() { proto.RegisterFile("gsdirectory.proto", fileDescriptor_a17fe7d4803e74ca) }

var fileDescriptor_a17fe7d4803e74ca = []byte{
	// 642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xf3, 0xd7, 0x64, 0x92, 0xb6, 0xee, 0x92, 0x52, 0xab, 0x42, 0x34, 0x58, 0xfc, 0x44,
	0x95, 0xa8, 0x50, 0xb9, 0x70, 0x85, 0x54, 0x98, 0x4a, 0x08, 0x55, 0x36, 0xb4, 0x47, 0xb4, 0xb5,
	0xb7, 0xa9, 0x55, 0xaf, 0x37, 0x5a, 0x6f, 0x1a, 0x7c, 0xe0, 0xc8, 0x13, 0x70, 0x47, 0x42, 0x88,
	0x87, 0x40, 0x88, 0xa7, 0xe0, 0x85, 0xd0, 0xac, 0x9d, 0xd8, 0xa6, 0x22, 0xa7, 0x8a, 0xdb, 0xcc,
	0x37, 0xeb, 0x99, 0x6f, 0xbe, 0x19, 0x0f, 0x6c, 0x8e, 0x93, 0x20, 0x94, 0xcc, 0x57, 0x42, 0xa6,
	0xfb, 0x13, 0x29, 0x94, 0x20, 0xad, 0x44, 0x49, 0x46, 0xf9, 0x4e, 0xcf, 0x17, 0x9c, 0x8b, 0x38,
	0x43, 0xed, 0x8f, 0xb0, 0xea, 0x78, 0xaf, 0xc5, 0x38, 0x8c, 0xc9, 0x6d, 0x68, 0x8d, 0x29, 0x67,
	0x47, 0x87, 0x96, 0x31, 0x30, 0x86, 0x6b, 0x6e, 0xee, 0x11, 0x0b, 0x56, 0x93, 0x2b, 0xff, 0x0d,
	0xe5, 0xcc, 0xaa, 0x0d, 0x8c, 0x61, 0xc7, 0x9d, 0xbb, 0x18, 0x99, 0x88, 0x40, 0x47, 0xea, 0x59,
	0x24, 0x77, 0x09, 0x81, 0xc6, 0x85, 0x48, 0x94, 0xd5, 0xd0, 0xb0, 0xb6, 0x11, 0x9b, 0x08, 0xa9,
	0xac, 0xa6, 0xce, 0xae, 0x6d, 0xfb, 0x3e, 0x40, 0x5e, 0xfe, 0xb9, 0x7f, 0x89, 0x0c, 0x12, 0x45,
	0xd5, 0x34, 0x99, 0x33, 0xc8, 0x3c, 0xfb, 0x1e, 0x74, 0x1d, 0xef, 0x15, 0xa3, 0x52, 0x9d, 0x31,
	0xaa, 0x13, 0x45, 0x82, 0x06, 0xf9, 0x23, 0x6d, 0xdb, 0x43, 0x58, 0x2f, 0x3d, 0x59, 0x96, 0xec,
	0x04, 0xda, 0xba, 0xa4, 0x98, 0xaa, 0x9b, 0x6c, 0xd9, 0x7e, 0x80, 0x24, 0xb3, 0xbc, 0xcb, 0xca,
	0x7f, 0xae, 0x41, 0xdb, 0x15, 0x82, 0x1f, 0xc5, 0xe7, 0x82, 0xec, 0x40, 0x4b, 0xa2, 0x9d, 0xd5,
	0x6f, 0xbc, 0xa8, 0x3d, 0x31, 0xdc, 0x1c, 0x21, 0x3b, 0xd0, 0x46, 0xab, 0x44, 0x62, 0xe1, 0x93,
	0x3b, 0xd0, 0xe1, 0xf4, 0xc3, 0x71, 0x44, 0x53, 0x26, 0x35, 0x8f, 0x35, 0xb7, 0x00, 0x50, 0x1f,
	0x2e, 0x02, 0xa6, 0xc5, 0x6f, 0xba, 0xda, 0xc6, 0x6c, 0x3e, 0x8d, 0x4f, 0xa9, 0xf2, 0x2f, 0xf4,
	0x00, 0x9a, 0xee, 0xc2, 0x27, 0x77, 0x01, 0xae, 0xc2, 0x24, 0x3c, 0x0b, 0xa3, 0x50, 0xa5, 0x56,
	0x4b, 0x47, 0x4b, 0x08, 0xb1, 0xa1, 0x87, 0x95, 0x8f, 0xa5, 0x98, 0x30, 0xa9, 0x52, 0x6b, 0x75,
	0x60, 0x0c, 0x7b, 0x6e, 0x05, 0x23, 0x7d, 0x68, 0x8a, 0x59, 0xcc, 0xa4, 0xd5, 0xd6, 0x6c, 0x32,
	0x87, 0x3c, 0x82, 0x26, 0xb6, 0xcd, 0xac, 0xce, 0xc0, 0x18, 0xae, 0x1f, 0x6c, 0xee, 0x67, 0x3b,
	0xb8, 0x8f, 0x02, 0x78, 0x18, 0x70, 0xb3, 0xb8, 0xfd, 0xdb, 0x00, 0x18, 0x49, 0x86, 0x88, 0x10,
	0xbc, 0xac, 0xbf, 0xf1, 0x4f, 0xfd, 0x6b, 0xd5, 0x95, 0x2b, 0x66, 0x59, 0xaf, 0xcc, 0xf2, 0x31,
	0x74, 0x90, 0xe9, 0xfb, 0x30, 0x3e, 0x17, 0x5a, 0x92, 0xee, 0x81, 0x59, 0xe6, 0x81, 0x83, 0xc8,
	0xa4, 0xd5, 0x23, 0x31, 0xa1, 0xae, 0x54, 0x94, 0x2f, 0x29, 0x9a, 0xe4, 0x19, 0xf4, 0x66, 0xa8,
	0x93, 0xc7, 0x94, 0x0a, 0xe3, 0xb1, 0x16, 0xa8, 0x7b, 0xd0, 0x9f, 0xe7, 0x38, 0x2d, 0xc5, 0xdc,
	0xca, 0x4b, 0x7b, 0x04, 0x6b, 0x45, 0x53, 0x4b, 0x96, 0xa2, 0xb4, 0x07, 0xb5, 0xbf, 0xf7, 0xc0,
	0xfe, 0x64, 0x40, 0xe7, 0xad, 0x98, 0xfa, 0x17, 0x37, 0xae, 0x4c, 0x51, 0xb5, 0x71, 0x6d, 0xfb,
	0xae, 0xc9, 0x60, 0x3f, 0x84, 0xde, 0x82, 0xc6, 0xb2, 0x05, 0x9f, 0x42, 0xf7, 0x90, 0x25, 0x4a,
	0x8a, 0xf4, 0x7f, 0x12, 0xc6, 0x03, 0x50, 0x2a, 0xbb, 0x84, 0xe0, 0xde, 0x17, 0x03, 0x4c, 0xc7,
	0x3b, 0x9c, 0x9f, 0xc7, 0x11, 0x0f, 0x74, 0xbf, 0xbd, 0xa3, 0xf8, 0x84, 0x46, 0x61, 0xe0, 0x78,
	0x23, 0x1e, 0x98, 0x2b, 0x64, 0x63, 0x71, 0x9a, 0xd0, 0xff, 0xb1, 0x4d, 0x6e, 0x55, 0x4e, 0x0c,
	0x82, 0x3f, 0xb7, 0x89, 0x59, 0xfc, 0xf5, 0x88, 0xfc, 0xda, 0x26, 0x7d, 0xd8, 0x70, 0xbc, 0x62,
	0xec, 0x88, 0x7e, 0xdd, 0xcd, 0x3e, 0x5e, 0xe8, 0x87, 0xe0, 0xb7, 0x5d, 0xb2, 0xa5, 0x89, 0x14,
	0xac, 0x11, 0xfe, 0xbe, 0xbb, 0x47, 0xe7, 0xff, 0xc2, 0xcb, 0x88, 0x8e, 0xc9, 0x16, 0x6c, 0x16,
	0xd9, 0xde, 0xc5, 0x97, 0xb1, 0x98, 0xc5, 0xe6, 0x0a, 0xe9, 0x83, 0x59, 0xc0, 0x5e, 0x9a, 0x28,
	0xc6, 0x4d, 0xa3, 0x8a, 0x66, 0xe7, 0xc0, 0xac, 0x61, 0x73, 0x05, 0xea, 0x78, 0x66, 0xfd, 0xac,
	0xa5, 0xaf, 0xff, 0xd3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x97, 0xb5, 0xb0, 0x28, 0x06,
	0x00, 0x00,
}
