// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gshotel.proto

package stream

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HotelGsCmdID int32

const (
	HotelGsCmdID_HotelNone HotelGsCmdID = 0
	//建立连接时
	HotelGsCmdID_HotelCreateConnect    HotelGsCmdID = 1501
	HotelGsCmdID_HotelCreateConnectAck HotelGsCmdID = 1502
	// 二进制broadcast协议
	HotelGsCmdID_HotelBroadcastCMDID    HotelGsCmdID = 1503
	HotelGsCmdID_HotelBroadcastAckCMDID HotelGsCmdID = 1504
	// 二进制push协议
	HotelGsCmdID_HotelPushCMDID HotelGsCmdID = 1505
	//删除房间
	HotelGsCmdID_HotelCloseConnet    HotelGsCmdID = 1506
	HotelGsCmdID_HotelCloseConnetAck HotelGsCmdID = 1507
	// 玩家checkin
	HotelGsCmdID_HotelPlayerCheckin    HotelGsCmdID = 1601
	HotelGsCmdID_HotelPlayerCheckinAck HotelGsCmdID = 1602
	// 设置帧率
	HotelGsCmdID_GSSetFrameSyncRateCMDID    HotelGsCmdID = 1603
	HotelGsCmdID_GSSetFrameSyncRateAckCMDID HotelGsCmdID = 1604
	// 设置帧率通知
	HotelGsCmdID_GSSetFrameSyncRateNotifyCMDID HotelGsCmdID = 1606
	// 发送帧数据
	HotelGsCmdID_GSFrameBroadcastCMDID    HotelGsCmdID = 1607
	HotelGsCmdID_GSFrameBroadcastAckCMDID HotelGsCmdID = 1608
	// 帧数据通知
	HotelGsCmdID_GSFrameDataNotifyCMDID HotelGsCmdID = 1610
	// 帧同步通知
	HotelGsCmdID_GSFrameSyncNotifyCMDID HotelGsCmdID = 1612
)

var HotelGsCmdID_name = map[int32]string{
	0:    "HotelNone",
	1501: "HotelCreateConnect",
	1502: "HotelCreateConnectAck",
	1503: "HotelBroadcastCMDID",
	1504: "HotelBroadcastAckCMDID",
	1505: "HotelPushCMDID",
	1506: "HotelCloseConnet",
	1507: "HotelCloseConnetAck",
	1601: "HotelPlayerCheckin",
	1602: "HotelPlayerCheckinAck",
	1603: "GSSetFrameSyncRateCMDID",
	1604: "GSSetFrameSyncRateAckCMDID",
	1606: "GSSetFrameSyncRateNotifyCMDID",
	1607: "GSFrameBroadcastCMDID",
	1608: "GSFrameBroadcastAckCMDID",
	1610: "GSFrameDataNotifyCMDID",
	1612: "GSFrameSyncNotifyCMDID",
}

var HotelGsCmdID_value = map[string]int32{
	"HotelNone":                     0,
	"HotelCreateConnect":            1501,
	"HotelCreateConnectAck":         1502,
	"HotelBroadcastCMDID":           1503,
	"HotelBroadcastAckCMDID":        1504,
	"HotelPushCMDID":                1505,
	"HotelCloseConnet":              1506,
	"HotelCloseConnetAck":           1507,
	"HotelPlayerCheckin":            1601,
	"HotelPlayerCheckinAck":         1602,
	"GSSetFrameSyncRateCMDID":       1603,
	"GSSetFrameSyncRateAckCMDID":    1604,
	"GSSetFrameSyncRateNotifyCMDID": 1606,
	"GSFrameBroadcastCMDID":         1607,
	"GSFrameBroadcastAckCMDID":      1608,
	"GSFrameDataNotifyCMDID":        1610,
	"GSFrameSyncNotifyCMDID":        1612,
}

func (x HotelGsCmdID) String() string {
	return proto.EnumName(HotelGsCmdID_name, int32(x))
}

func (HotelGsCmdID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{0}
}

//推送hotel消息类型
type PushMsgType int32

const (
	PushMsgType_NoneType PushMsgType = 0
	//推送给列表中的指定用户
	PushMsgType_UserTypeSpecific PushMsgType = 1
	//推送给除列表中指定用户外的其他用户
	PushMsgType_UserTypeExclude PushMsgType = 2
	//推送给房间内的所有用户，包括自己，users列表参数无效
	PushMsgType_UserTypeAll PushMsgType = 3
)

var PushMsgType_name = map[int32]string{
	0: "NoneType",
	1: "UserTypeSpecific",
	2: "UserTypeExclude",
	3: "UserTypeAll",
}

var PushMsgType_value = map[string]int32{
	"NoneType":         0,
	"UserTypeSpecific": 1,
	"UserTypeExclude":  2,
	"UserTypeAll":      3,
}

func (x PushMsgType) String() string {
	return proto.EnumName(PushMsgType_name, int32(x))
}

func (PushMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{1}
}

//建立连接时//需要把roomID和Stream映射起来
type Connect struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{0}
}

func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (m *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(m, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *Connect) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

//建立连接后返回
type ConnectAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectAck) Reset()         { *m = ConnectAck{} }
func (m *ConnectAck) String() string { return proto.CompactTextString(m) }
func (*ConnectAck) ProtoMessage()    {}
func (*ConnectAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{1}
}

func (m *ConnectAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectAck.Unmarshal(m, b)
}
func (m *ConnectAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectAck.Marshal(b, m, deterministic)
}
func (m *ConnectAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectAck.Merge(m, src)
}
func (m *ConnectAck) XXX_Size() int {
	return xxx_messageInfo_ConnectAck.Size(m)
}
func (m *ConnectAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectAck.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectAck proto.InternalMessageInfo

func (m *ConnectAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//关闭连接，删除房间信息
type CloseConnect struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseConnect) Reset()         { *m = CloseConnect{} }
func (m *CloseConnect) String() string { return proto.CompactTextString(m) }
func (*CloseConnect) ProtoMessage()    {}
func (*CloseConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{2}
}

func (m *CloseConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseConnect.Unmarshal(m, b)
}
func (m *CloseConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseConnect.Marshal(b, m, deterministic)
}
func (m *CloseConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseConnect.Merge(m, src)
}
func (m *CloseConnect) XXX_Size() int {
	return xxx_messageInfo_CloseConnect.Size(m)
}
func (m *CloseConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseConnect.DiscardUnknown(m)
}

var xxx_messageInfo_CloseConnect proto.InternalMessageInfo

func (m *CloseConnect) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *CloseConnect) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

//关闭连接返回
type CloseConnectAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseConnectAck) Reset()         { *m = CloseConnectAck{} }
func (m *CloseConnectAck) String() string { return proto.CompactTextString(m) }
func (*CloseConnectAck) ProtoMessage()    {}
func (*CloseConnectAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{3}
}

func (m *CloseConnectAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseConnectAck.Unmarshal(m, b)
}
func (m *CloseConnectAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseConnectAck.Marshal(b, m, deterministic)
}
func (m *CloseConnectAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseConnectAck.Merge(m, src)
}
func (m *CloseConnectAck) XXX_Size() int {
	return xxx_messageInfo_CloseConnectAck.Size(m)
}
func (m *CloseConnectAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseConnectAck.DiscardUnknown(m)
}

var xxx_messageInfo_CloseConnectAck proto.InternalMessageInfo

func (m *CloseConnectAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//广播消息
type HotelBroadcast struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	GameID               uint32   `protobuf:"varint,2,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Flag                 uint32   `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`
	DstUids              []uint32 `protobuf:"varint,5,rep,packed,name=dstUids,proto3" json:"dstUids,omitempty"`
	CpProto              []byte   `protobuf:"bytes,6,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotelBroadcast) Reset()         { *m = HotelBroadcast{} }
func (m *HotelBroadcast) String() string { return proto.CompactTextString(m) }
func (*HotelBroadcast) ProtoMessage()    {}
func (*HotelBroadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{4}
}

func (m *HotelBroadcast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotelBroadcast.Unmarshal(m, b)
}
func (m *HotelBroadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotelBroadcast.Marshal(b, m, deterministic)
}
func (m *HotelBroadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotelBroadcast.Merge(m, src)
}
func (m *HotelBroadcast) XXX_Size() int {
	return xxx_messageInfo_HotelBroadcast.Size(m)
}
func (m *HotelBroadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_HotelBroadcast.DiscardUnknown(m)
}

var xxx_messageInfo_HotelBroadcast proto.InternalMessageInfo

func (m *HotelBroadcast) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *HotelBroadcast) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *HotelBroadcast) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *HotelBroadcast) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *HotelBroadcast) GetDstUids() []uint32 {
	if m != nil {
		return m.DstUids
	}
	return nil
}

func (m *HotelBroadcast) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

//消息同步返回
type HotelBroadcastAck struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotelBroadcastAck) Reset()         { *m = HotelBroadcastAck{} }
func (m *HotelBroadcastAck) String() string { return proto.CompactTextString(m) }
func (*HotelBroadcastAck) ProtoMessage()    {}
func (*HotelBroadcastAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{5}
}

func (m *HotelBroadcastAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotelBroadcastAck.Unmarshal(m, b)
}
func (m *HotelBroadcastAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotelBroadcastAck.Marshal(b, m, deterministic)
}
func (m *HotelBroadcastAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotelBroadcastAck.Merge(m, src)
}
func (m *HotelBroadcastAck) XXX_Size() int {
	return xxx_messageInfo_HotelBroadcastAck.Size(m)
}
func (m *HotelBroadcastAck) XXX_DiscardUnknown() {
	xxx_messageInfo_HotelBroadcastAck.DiscardUnknown(m)
}

var xxx_messageInfo_HotelBroadcastAck proto.InternalMessageInfo

func (m *HotelBroadcastAck) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *HotelBroadcastAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//推送给hotel消息
type PushToHotelMsg struct {
	PushType             PushMsgType `protobuf:"varint,1,opt,name=pushType,proto3,enum=stream.PushMsgType" json:"pushType,omitempty"`
	GameID               uint32      `protobuf:"varint,2,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64      `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	DstUids              []uint32    `protobuf:"varint,4,rep,packed,name=dstUids,proto3" json:"dstUids,omitempty"`
	CpProto              []byte      `protobuf:"bytes,5,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PushToHotelMsg) Reset()         { *m = PushToHotelMsg{} }
func (m *PushToHotelMsg) String() string { return proto.CompactTextString(m) }
func (*PushToHotelMsg) ProtoMessage()    {}
func (*PushToHotelMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{6}
}

func (m *PushToHotelMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushToHotelMsg.Unmarshal(m, b)
}
func (m *PushToHotelMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushToHotelMsg.Marshal(b, m, deterministic)
}
func (m *PushToHotelMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushToHotelMsg.Merge(m, src)
}
func (m *PushToHotelMsg) XXX_Size() int {
	return xxx_messageInfo_PushToHotelMsg.Size(m)
}
func (m *PushToHotelMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushToHotelMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PushToHotelMsg proto.InternalMessageInfo

func (m *PushToHotelMsg) GetPushType() PushMsgType {
	if m != nil {
		return m.PushType
	}
	return PushMsgType_NoneType
}

func (m *PushToHotelMsg) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *PushToHotelMsg) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *PushToHotelMsg) GetDstUids() []uint32 {
	if m != nil {
		return m.DstUids
	}
	return nil
}

func (m *PushToHotelMsg) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

//玩家checkin消息
type PlayerCheckin struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	GameID               uint32   `protobuf:"varint,2,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	MaxPlayers           uint32   `protobuf:"varint,4,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	Checkins             []uint32 `protobuf:"varint,5,rep,packed,name=checkins,proto3" json:"checkins,omitempty"`
	Players              []uint32 `protobuf:"varint,6,rep,packed,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerCheckin) Reset()         { *m = PlayerCheckin{} }
func (m *PlayerCheckin) String() string { return proto.CompactTextString(m) }
func (*PlayerCheckin) ProtoMessage()    {}
func (*PlayerCheckin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{7}
}

func (m *PlayerCheckin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCheckin.Unmarshal(m, b)
}
func (m *PlayerCheckin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCheckin.Marshal(b, m, deterministic)
}
func (m *PlayerCheckin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCheckin.Merge(m, src)
}
func (m *PlayerCheckin) XXX_Size() int {
	return xxx_messageInfo_PlayerCheckin.Size(m)
}
func (m *PlayerCheckin) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCheckin.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCheckin proto.InternalMessageInfo

func (m *PlayerCheckin) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *PlayerCheckin) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *PlayerCheckin) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *PlayerCheckin) GetMaxPlayers() uint32 {
	if m != nil {
		return m.MaxPlayers
	}
	return 0
}

func (m *PlayerCheckin) GetCheckins() []uint32 {
	if m != nil {
		return m.Checkins
	}
	return nil
}

func (m *PlayerCheckin) GetPlayers() []uint32 {
	if m != nil {
		return m.Players
	}
	return nil
}

//玩家checkin消息返回
type PlayerCheckinAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerCheckinAck) Reset()         { *m = PlayerCheckinAck{} }
func (m *PlayerCheckinAck) String() string { return proto.CompactTextString(m) }
func (*PlayerCheckinAck) ProtoMessage()    {}
func (*PlayerCheckinAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{8}
}

func (m *PlayerCheckinAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCheckinAck.Unmarshal(m, b)
}
func (m *PlayerCheckinAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCheckinAck.Marshal(b, m, deterministic)
}
func (m *PlayerCheckinAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCheckinAck.Merge(m, src)
}
func (m *PlayerCheckinAck) XXX_Size() int {
	return xxx_messageInfo_PlayerCheckinAck.Size(m)
}
func (m *PlayerCheckinAck) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCheckinAck.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCheckinAck proto.InternalMessageInfo

func (m *PlayerCheckinAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GSSetFrameSyncRate struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Priority             uint32   `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	FrameRate            uint32   `protobuf:"varint,4,opt,name=frameRate,proto3" json:"frameRate,omitempty"`
	FrameIdx             uint32   `protobuf:"varint,5,opt,name=frameIdx,proto3" json:"frameIdx,omitempty"`
	EnableGS             uint32   `protobuf:"varint,6,opt,name=enableGS,proto3" json:"enableGS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSSetFrameSyncRate) Reset()         { *m = GSSetFrameSyncRate{} }
func (m *GSSetFrameSyncRate) String() string { return proto.CompactTextString(m) }
func (*GSSetFrameSyncRate) ProtoMessage()    {}
func (*GSSetFrameSyncRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{9}
}

func (m *GSSetFrameSyncRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSSetFrameSyncRate.Unmarshal(m, b)
}
func (m *GSSetFrameSyncRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSSetFrameSyncRate.Marshal(b, m, deterministic)
}
func (m *GSSetFrameSyncRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSSetFrameSyncRate.Merge(m, src)
}
func (m *GSSetFrameSyncRate) XXX_Size() int {
	return xxx_messageInfo_GSSetFrameSyncRate.Size(m)
}
func (m *GSSetFrameSyncRate) XXX_DiscardUnknown() {
	xxx_messageInfo_GSSetFrameSyncRate.DiscardUnknown(m)
}

var xxx_messageInfo_GSSetFrameSyncRate proto.InternalMessageInfo

func (m *GSSetFrameSyncRate) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *GSSetFrameSyncRate) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *GSSetFrameSyncRate) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *GSSetFrameSyncRate) GetFrameRate() uint32 {
	if m != nil {
		return m.FrameRate
	}
	return 0
}

func (m *GSSetFrameSyncRate) GetFrameIdx() uint32 {
	if m != nil {
		return m.FrameIdx
	}
	return 0
}

func (m *GSSetFrameSyncRate) GetEnableGS() uint32 {
	if m != nil {
		return m.EnableGS
	}
	return 0
}

type GSSetFrameSyncRateAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSSetFrameSyncRateAck) Reset()         { *m = GSSetFrameSyncRateAck{} }
func (m *GSSetFrameSyncRateAck) String() string { return proto.CompactTextString(m) }
func (*GSSetFrameSyncRateAck) ProtoMessage()    {}
func (*GSSetFrameSyncRateAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{10}
}

func (m *GSSetFrameSyncRateAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSSetFrameSyncRateAck.Unmarshal(m, b)
}
func (m *GSSetFrameSyncRateAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSSetFrameSyncRateAck.Marshal(b, m, deterministic)
}
func (m *GSSetFrameSyncRateAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSSetFrameSyncRateAck.Merge(m, src)
}
func (m *GSSetFrameSyncRateAck) XXX_Size() int {
	return xxx_messageInfo_GSSetFrameSyncRateAck.Size(m)
}
func (m *GSSetFrameSyncRateAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GSSetFrameSyncRateAck.DiscardUnknown(m)
}

var xxx_messageInfo_GSSetFrameSyncRateAck proto.InternalMessageInfo

func (m *GSSetFrameSyncRateAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GSSetFrameSyncRateNotify struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Priority             uint32   `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	FrameRate            uint32   `protobuf:"varint,4,opt,name=frameRate,proto3" json:"frameRate,omitempty"`
	FrameIdx             uint32   `protobuf:"varint,5,opt,name=frameIdx,proto3" json:"frameIdx,omitempty"`
	TimeStamp            uint64   `protobuf:"varint,6,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	EnableGS             uint32   `protobuf:"varint,7,opt,name=enableGS,proto3" json:"enableGS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSSetFrameSyncRateNotify) Reset()         { *m = GSSetFrameSyncRateNotify{} }
func (m *GSSetFrameSyncRateNotify) String() string { return proto.CompactTextString(m) }
func (*GSSetFrameSyncRateNotify) ProtoMessage()    {}
func (*GSSetFrameSyncRateNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{11}
}

func (m *GSSetFrameSyncRateNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSSetFrameSyncRateNotify.Unmarshal(m, b)
}
func (m *GSSetFrameSyncRateNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSSetFrameSyncRateNotify.Marshal(b, m, deterministic)
}
func (m *GSSetFrameSyncRateNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSSetFrameSyncRateNotify.Merge(m, src)
}
func (m *GSSetFrameSyncRateNotify) XXX_Size() int {
	return xxx_messageInfo_GSSetFrameSyncRateNotify.Size(m)
}
func (m *GSSetFrameSyncRateNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_GSSetFrameSyncRateNotify.DiscardUnknown(m)
}

var xxx_messageInfo_GSSetFrameSyncRateNotify proto.InternalMessageInfo

func (m *GSSetFrameSyncRateNotify) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *GSSetFrameSyncRateNotify) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *GSSetFrameSyncRateNotify) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *GSSetFrameSyncRateNotify) GetFrameRate() uint32 {
	if m != nil {
		return m.FrameRate
	}
	return 0
}

func (m *GSSetFrameSyncRateNotify) GetFrameIdx() uint32 {
	if m != nil {
		return m.FrameIdx
	}
	return 0
}

func (m *GSSetFrameSyncRateNotify) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *GSSetFrameSyncRateNotify) GetEnableGS() uint32 {
	if m != nil {
		return m.EnableGS
	}
	return 0
}

type GSFrameBroadcast struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Priority             uint32   `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	CpProto              []byte   `protobuf:"bytes,4,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	Operation            int32    `protobuf:"varint,5,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSFrameBroadcast) Reset()         { *m = GSFrameBroadcast{} }
func (m *GSFrameBroadcast) String() string { return proto.CompactTextString(m) }
func (*GSFrameBroadcast) ProtoMessage()    {}
func (*GSFrameBroadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{12}
}

func (m *GSFrameBroadcast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSFrameBroadcast.Unmarshal(m, b)
}
func (m *GSFrameBroadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSFrameBroadcast.Marshal(b, m, deterministic)
}
func (m *GSFrameBroadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSFrameBroadcast.Merge(m, src)
}
func (m *GSFrameBroadcast) XXX_Size() int {
	return xxx_messageInfo_GSFrameBroadcast.Size(m)
}
func (m *GSFrameBroadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_GSFrameBroadcast.DiscardUnknown(m)
}

var xxx_messageInfo_GSFrameBroadcast proto.InternalMessageInfo

func (m *GSFrameBroadcast) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *GSFrameBroadcast) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *GSFrameBroadcast) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *GSFrameBroadcast) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

func (m *GSFrameBroadcast) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

type GSFrameBroadcastAck struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSFrameBroadcastAck) Reset()         { *m = GSFrameBroadcastAck{} }
func (m *GSFrameBroadcastAck) String() string { return proto.CompactTextString(m) }
func (*GSFrameBroadcastAck) ProtoMessage()    {}
func (*GSFrameBroadcastAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{13}
}

func (m *GSFrameBroadcastAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSFrameBroadcastAck.Unmarshal(m, b)
}
func (m *GSFrameBroadcastAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSFrameBroadcastAck.Marshal(b, m, deterministic)
}
func (m *GSFrameBroadcastAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSFrameBroadcastAck.Merge(m, src)
}
func (m *GSFrameBroadcastAck) XXX_Size() int {
	return xxx_messageInfo_GSFrameBroadcastAck.Size(m)
}
func (m *GSFrameBroadcastAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GSFrameBroadcastAck.DiscardUnknown(m)
}

var xxx_messageInfo_GSFrameBroadcastAck proto.InternalMessageInfo

func (m *GSFrameBroadcastAck) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GSFrameDataNotify struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	SrcUid               uint32   `protobuf:"varint,3,opt,name=src_uid,json=srcUid,proto3" json:"src_uid,omitempty"`
	Priority             uint32   `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	CpProto              []byte   `protobuf:"bytes,5,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	TimeStamp            uint64   `protobuf:"varint,6,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	FrameIdx             uint32   `protobuf:"varint,7,opt,name=frameIdx,proto3" json:"frameIdx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSFrameDataNotify) Reset()         { *m = GSFrameDataNotify{} }
func (m *GSFrameDataNotify) String() string { return proto.CompactTextString(m) }
func (*GSFrameDataNotify) ProtoMessage()    {}
func (*GSFrameDataNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{14}
}

func (m *GSFrameDataNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSFrameDataNotify.Unmarshal(m, b)
}
func (m *GSFrameDataNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSFrameDataNotify.Marshal(b, m, deterministic)
}
func (m *GSFrameDataNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSFrameDataNotify.Merge(m, src)
}
func (m *GSFrameDataNotify) XXX_Size() int {
	return xxx_messageInfo_GSFrameDataNotify.Size(m)
}
func (m *GSFrameDataNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_GSFrameDataNotify.DiscardUnknown(m)
}

var xxx_messageInfo_GSFrameDataNotify proto.InternalMessageInfo

func (m *GSFrameDataNotify) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *GSFrameDataNotify) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *GSFrameDataNotify) GetSrcUid() uint32 {
	if m != nil {
		return m.SrcUid
	}
	return 0
}

func (m *GSFrameDataNotify) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *GSFrameDataNotify) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

func (m *GSFrameDataNotify) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *GSFrameDataNotify) GetFrameIdx() uint32 {
	if m != nil {
		return m.FrameIdx
	}
	return 0
}

type GSFrameSyncNotify struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Priority             uint32   `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	LastIdx              uint32   `protobuf:"varint,4,opt,name=lastIdx,proto3" json:"lastIdx,omitempty"`
	NextIdx              uint32   `protobuf:"varint,5,opt,name=nextIdx,proto3" json:"nextIdx,omitempty"`
	StartTS              uint64   `protobuf:"varint,6,opt,name=startTS,proto3" json:"startTS,omitempty"`
	EndTS                uint64   `protobuf:"varint,7,opt,name=endTS,proto3" json:"endTS,omitempty"`
	TimeStamp            uint64   `protobuf:"varint,8,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSFrameSyncNotify) Reset()         { *m = GSFrameSyncNotify{} }
func (m *GSFrameSyncNotify) String() string { return proto.CompactTextString(m) }
func (*GSFrameSyncNotify) ProtoMessage()    {}
func (*GSFrameSyncNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08d036b9d9d1336, []int{15}
}

func (m *GSFrameSyncNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSFrameSyncNotify.Unmarshal(m, b)
}
func (m *GSFrameSyncNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSFrameSyncNotify.Marshal(b, m, deterministic)
}
func (m *GSFrameSyncNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSFrameSyncNotify.Merge(m, src)
}
func (m *GSFrameSyncNotify) XXX_Size() int {
	return xxx_messageInfo_GSFrameSyncNotify.Size(m)
}
func (m *GSFrameSyncNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_GSFrameSyncNotify.DiscardUnknown(m)
}

var xxx_messageInfo_GSFrameSyncNotify proto.InternalMessageInfo

func (m *GSFrameSyncNotify) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *GSFrameSyncNotify) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *GSFrameSyncNotify) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *GSFrameSyncNotify) GetLastIdx() uint32 {
	if m != nil {
		return m.LastIdx
	}
	return 0
}

func (m *GSFrameSyncNotify) GetNextIdx() uint32 {
	if m != nil {
		return m.NextIdx
	}
	return 0
}

func (m *GSFrameSyncNotify) GetStartTS() uint64 {
	if m != nil {
		return m.StartTS
	}
	return 0
}

func (m *GSFrameSyncNotify) GetEndTS() uint64 {
	if m != nil {
		return m.EndTS
	}
	return 0
}

func (m *GSFrameSyncNotify) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("stream.HotelGsCmdID", HotelGsCmdID_name, HotelGsCmdID_value)
	proto.RegisterEnum("stream.PushMsgType", PushMsgType_name, PushMsgType_value)
	proto.RegisterType((*Connect)(nil), "stream.Connect")
	proto.RegisterType((*ConnectAck)(nil), "stream.ConnectAck")
	proto.RegisterType((*CloseConnect)(nil), "stream.CloseConnect")
	proto.RegisterType((*CloseConnectAck)(nil), "stream.CloseConnectAck")
	proto.RegisterType((*HotelBroadcast)(nil), "stream.HotelBroadcast")
	proto.RegisterType((*HotelBroadcastAck)(nil), "stream.HotelBroadcastAck")
	proto.RegisterType((*PushToHotelMsg)(nil), "stream.PushToHotelMsg")
	proto.RegisterType((*PlayerCheckin)(nil), "stream.PlayerCheckin")
	proto.RegisterType((*PlayerCheckinAck)(nil), "stream.PlayerCheckinAck")
	proto.RegisterType((*GSSetFrameSyncRate)(nil), "stream.GSSetFrameSyncRate")
	proto.RegisterType((*GSSetFrameSyncRateAck)(nil), "stream.GSSetFrameSyncRateAck")
	proto.RegisterType((*GSSetFrameSyncRateNotify)(nil), "stream.GSSetFrameSyncRateNotify")
	proto.RegisterType((*GSFrameBroadcast)(nil), "stream.GSFrameBroadcast")
	proto.RegisterType((*GSFrameBroadcastAck)(nil), "stream.GSFrameBroadcastAck")
	proto.RegisterType((*GSFrameDataNotify)(nil), "stream.GSFrameDataNotify")
	proto.RegisterType((*GSFrameSyncNotify)(nil), "stream.GSFrameSyncNotify")
}

func init() { proto.RegisterFile("gshotel.proto", fileDescriptor_c08d036b9d9d1336) }

var fileDescriptor_c08d036b9d9d1336 = []byte{
	// 845 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcd, 0x6f, 0xe3, 0x44,
	0x14, 0x5f, 0xb7, 0x4e, 0xd2, 0x3e, 0xdb, 0xad, 0x77, 0xb2, 0xdd, 0x5a, 0xa5, 0x0b, 0x91, 0xc5,
	0x21, 0x54, 0xa2, 0x2b, 0xc1, 0x89, 0x0b, 0x52, 0x49, 0x20, 0xe4, 0xd0, 0x55, 0x65, 0xb7, 0xe2,
	0x88, 0x66, 0xed, 0x49, 0x6a, 0xd5, 0x5f, 0xf2, 0x4c, 0xa4, 0xe4, 0x1f, 0xe1, 0xcc, 0x85, 0x23,
	0x57, 0xee, 0x7c, 0x08, 0x10, 0xda, 0xbf, 0x00, 0xf1, 0xb5, 0xf0, 0x8f, 0xa0, 0x99, 0xf1, 0x67,
	0x4c, 0x22, 0xed, 0x6a, 0x91, 0xf6, 0xe6, 0xdf, 0x7b, 0x33, 0xf3, 0x7e, 0xbf, 0x79, 0x6f, 0xde,
	0x33, 0x18, 0x73, 0x7a, 0x9b, 0x30, 0x12, 0x9e, 0xa7, 0x59, 0xc2, 0x12, 0xd4, 0xa5, 0x2c, 0x23,
	0x38, 0xb2, 0x3f, 0x80, 0xde, 0x28, 0x89, 0x63, 0xe2, 0x31, 0xf4, 0x10, 0xba, 0x73, 0x1c, 0x91,
	0xe9, 0xd8, 0x52, 0x06, 0xca, 0xd0, 0x70, 0x72, 0xc4, 0xed, 0x59, 0x92, 0x44, 0xd3, 0xb1, 0xb5,
	0x33, 0x50, 0x86, 0xaa, 0x93, 0x23, 0xfb, 0x6d, 0x80, 0x7c, 0xeb, 0x85, 0x77, 0xc7, 0x57, 0x51,
	0x86, 0xd9, 0x82, 0x16, 0xbb, 0x25, 0xb2, 0x3f, 0x04, 0x7d, 0x14, 0x26, 0x94, 0xbc, 0x6c, 0x94,
	0x77, 0xe0, 0xb0, 0xbe, 0x7f, 0x5b, 0xa8, 0x2f, 0x15, 0x38, 0xf8, 0x94, 0x6b, 0xfc, 0x28, 0x4b,
	0xb0, 0xef, 0x61, 0x2a, 0xa2, 0x2d, 0x28, 0xc9, 0xaa, 0x68, 0x12, 0xd5, 0x58, 0xec, 0x6c, 0x60,
	0xb1, 0x5b, 0x67, 0x81, 0x10, 0xa8, 0xb3, 0x10, 0xcf, 0x2d, 0x55, 0xac, 0x16, 0xdf, 0xc8, 0x82,
	0x9e, 0x4f, 0xd9, 0x4d, 0xe0, 0x53, 0xab, 0x33, 0xd8, 0x1d, 0x1a, 0x4e, 0x01, 0xb9, 0xc7, 0x4b,
	0xaf, 0xf8, 0x3d, 0x5b, 0xdd, 0x81, 0x32, 0xd4, 0x9d, 0x02, 0xda, 0x23, 0xb8, 0xdf, 0x64, 0x98,
	0xeb, 0xd9, 0x44, 0x32, 0xd7, 0xb9, 0xd3, 0xd0, 0xf9, 0x95, 0x02, 0x07, 0x57, 0x0b, 0x7a, 0x7b,
	0x9d, 0x88, 0xb3, 0x2e, 0xe9, 0x1c, 0x3d, 0x86, 0xbd, 0x94, 0x5b, 0x56, 0x29, 0x11, 0x87, 0x1c,
	0xbc, 0xd7, 0x3f, 0x97, 0x19, 0x3e, 0xe7, 0x2b, 0x2f, 0xe9, 0x9c, 0xbb, 0x9c, 0x72, 0xd1, 0x0b,
	0x5f, 0x40, 0x4d, 0xac, 0xba, 0x51, 0x6c, 0xa7, 0x29, 0xf6, 0x6b, 0x05, 0x8c, 0xab, 0x10, 0xaf,
	0x48, 0x36, 0xba, 0x25, 0xde, 0x5d, 0x10, 0xbf, 0xb2, 0x74, 0xbc, 0x09, 0x10, 0xe1, 0xa5, 0x3c,
	0x9b, 0xe6, 0x49, 0xa9, 0x59, 0xd0, 0x09, 0xec, 0x79, 0x32, 0x64, 0x91, 0x9b, 0x12, 0x73, 0xbe,
	0x69, 0xbe, 0xb1, 0x2b, 0x95, 0xe4, 0xd0, 0x3e, 0x03, 0xb3, 0x41, 0x77, 0x5b, 0xad, 0x7d, 0xa3,
	0x00, 0x9a, 0xb8, 0x2e, 0x61, 0x9f, 0x64, 0x38, 0x22, 0xee, 0x2a, 0xf6, 0x1c, 0xcc, 0xc8, 0x8b,
	0x56, 0x37, 0x27, 0x9a, 0x66, 0x41, 0x92, 0x05, 0x6c, 0x25, 0x24, 0x1a, 0x4e, 0x89, 0xd1, 0x29,
	0xec, 0xcf, 0xf8, 0xe1, 0xfc, 0xe0, 0x5c, 0x63, 0x65, 0xe0, 0x3b, 0x05, 0x98, 0xfa, 0x4b, 0x71,
	0xef, 0x86, 0x53, 0x62, 0xee, 0x23, 0x31, 0x7e, 0x1a, 0x92, 0x89, 0x2b, 0x0a, 0xd0, 0x70, 0x4a,
	0x6c, 0x3f, 0x86, 0xa3, 0x36, 0xef, 0x6d, 0x4a, 0x7f, 0x55, 0xc0, 0x6a, 0xef, 0x78, 0x92, 0xb0,
	0x60, 0xb6, 0x7a, 0x4d, 0xf4, 0x9e, 0xc2, 0x3e, 0x0b, 0x22, 0xe2, 0x32, 0x1c, 0xa5, 0x42, 0xb0,
	0xea, 0x54, 0x86, 0xc6, 0x6d, 0xf4, 0xd6, 0x6e, 0xe3, 0x0b, 0x05, 0xcc, 0x89, 0x2b, 0x94, 0x35,
	0x9a, 0xc6, 0x2b, 0x13, 0x55, 0x7b, 0x1d, 0x6a, 0xe3, 0x75, 0x70, 0xd2, 0x49, 0x4a, 0x32, 0xcc,
	0x82, 0x24, 0x16, 0x8a, 0x3a, 0x4e, 0x65, 0xb0, 0xdf, 0x85, 0xfe, 0x3a, 0xaf, 0x6d, 0x49, 0x7a,
	0xa6, 0xc0, 0xfd, 0x7c, 0xfd, 0x18, 0x33, 0xfc, 0x92, 0xd9, 0x39, 0x86, 0x1e, 0xcd, 0xbc, 0xcf,
	0x17, 0x81, 0x9f, 0xeb, 0xe8, 0xd2, 0xcc, 0xbb, 0x09, 0xfc, 0x86, 0x42, 0x75, 0xb3, 0xc2, 0x4e,
	0x4b, 0xe1, 0xf6, 0xb4, 0x94, 0x09, 0xed, 0x35, 0x13, 0x6a, 0x3f, 0xaf, 0xe4, 0xf0, 0x82, 0xfb,
	0x1f, 0x8a, 0xcd, 0x82, 0x5e, 0x88, 0x29, 0xe3, 0xc1, 0xa5, 0xa0, 0x02, 0x72, 0x4f, 0x4c, 0x96,
	0xac, 0xaa, 0xb3, 0x02, 0x72, 0x0f, 0x65, 0x38, 0x63, 0xd7, 0x6e, 0xae, 0xa6, 0x80, 0xe8, 0x01,
	0x74, 0x48, 0xec, 0x5f, 0xcb, 0xfa, 0x52, 0x1d, 0x09, 0x9a, 0xfa, 0xf7, 0xd6, 0xf4, 0x9f, 0xfd,
	0xb6, 0x0b, 0xba, 0xe8, 0xdf, 0x13, 0x3a, 0x8a, 0xfc, 0xe9, 0x18, 0x19, 0xb0, 0x2f, 0xf0, 0x93,
	0x24, 0x26, 0xe6, 0x3d, 0x74, 0x0c, 0x48, 0xc0, 0x51, 0x46, 0x30, 0x2b, 0xc6, 0x9f, 0xf9, 0xbb,
	0x86, 0x4e, 0xe0, 0xa8, 0xed, 0xb8, 0xf0, 0xee, 0xcc, 0x3f, 0x34, 0x64, 0x41, 0xbf, 0x39, 0x5f,
	0x46, 0x97, 0xe3, 0xe9, 0xd8, 0xfc, 0x53, 0x43, 0x6f, 0xc0, 0xc3, 0xd6, 0xe4, 0x91, 0xce, 0xbf,
	0x34, 0xd4, 0xcf, 0x07, 0x27, 0x9f, 0x15, 0xd2, 0xf8, 0x5c, 0x43, 0x47, 0x60, 0xca, 0x38, 0xe5,
	0xf8, 0x65, 0xe6, 0xdf, 0x55, 0x88, 0x9a, 0x99, 0x07, 0xff, 0x47, 0x2b, 0x19, 0x37, 0x9a, 0xa8,
	0xf9, 0xad, 0x5e, 0x32, 0x5e, 0xef, 0xae, 0xe6, 0x77, 0x3a, 0x3a, 0x85, 0xe3, 0x76, 0x77, 0x91,
	0x1c, 0xbe, 0xd7, 0xd1, 0x5b, 0x70, 0xf2, 0x9f, 0xdd, 0x4a, 0x2e, 0xf8, 0x41, 0x47, 0x36, 0x3c,
	0xda, 0xd4, 0x9c, 0xe4, 0x9a, 0x1f, 0x45, 0xf8, 0xf5, 0xb7, 0x24, 0x7d, 0x3f, 0xe9, 0xe8, 0x11,
	0x6f, 0x6e, 0xad, 0x77, 0x26, 0xdd, 0x3f, 0xeb, 0xfc, 0xd6, 0x5a, 0xcf, 0x4a, 0x3a, 0x7f, 0xa9,
	0x3b, 0xab, 0x22, 0x95, 0xce, 0x67, 0xfa, 0xd9, 0x67, 0xa0, 0xd5, 0x26, 0x2f, 0xd2, 0x61, 0x8f,
	0xe7, 0x95, 0x7f, 0x9b, 0xf7, 0xd0, 0x03, 0x30, 0x6f, 0x28, 0xc9, 0x38, 0x72, 0x53, 0xe2, 0x05,
	0xb3, 0xc0, 0x33, 0x15, 0xd4, 0x87, 0xc3, 0xc2, 0xfa, 0xf1, 0xd2, 0x0b, 0x17, 0x3e, 0x31, 0x77,
	0xd0, 0x21, 0x68, 0x85, 0xf1, 0x22, 0x0c, 0xcd, 0xdd, 0xa7, 0x5d, 0xf1, 0x03, 0xf7, 0xfe, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x56, 0xe9, 0x23, 0xd1, 0x09, 0x00, 0x00,
}
