// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gsmvs.proto

package stream

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MvsGsCmdID int32

const (
	MvsGsCmdID_MvsCmdNone            MvsGsCmdID = 0
	MvsGsCmdID_MvsJoinRoomReq        MvsGsCmdID = 1201
	MvsGsCmdID_MvsJoinRoomRsp        MvsGsCmdID = 1202
	MvsGsCmdID_MvsCreateRoomReq      MvsGsCmdID = 1203
	MvsGsCmdID_MvsCreateRoomRsp      MvsGsCmdID = 1204
	MvsGsCmdID_MvsLeaveRoomReq       MvsGsCmdID = 1205
	MvsGsCmdID_MvsLeaveRoomRsp       MvsGsCmdID = 1206
	MvsGsCmdID_MvsGetRoomDetailReq   MvsGsCmdID = 1209
	MvsGsCmdID_MvsGetRoomDetailRsp   MvsGsCmdID = 1210
	MvsGsCmdID_MvsGetRoomDetailPush  MvsGsCmdID = 1211
	MvsGsCmdID_MvsJoinOverReq        MvsGsCmdID = 1213
	MvsGsCmdID_MvsJoinOverRsp        MvsGsCmdID = 1214
	MvsGsCmdID_MvsSetRoomPropertyReq MvsGsCmdID = 1219
	MvsGsCmdID_MvsSetRoomPropertyRsp MvsGsCmdID = 1220
	MvsGsCmdID_MvsJoinOpenReq        MvsGsCmdID = 1221
	MvsGsCmdID_MvsJoinOpenRsp        MvsGsCmdID = 1222
	MvsGsCmdID_MvsKickPlayerReq      MvsGsCmdID = 1303
	MvsGsCmdID_MvsKickPlayerRsp      MvsGsCmdID = 1304
	MvsGsCmdID_MvsNetworkStateReq    MvsGsCmdID = 1120
	MvsGsCmdID_MvsNetworkStateRsp    MvsGsCmdID = 1121
)

var MvsGsCmdID_name = map[int32]string{
	0:    "MvsCmdNone",
	1201: "MvsJoinRoomReq",
	1202: "MvsJoinRoomRsp",
	1203: "MvsCreateRoomReq",
	1204: "MvsCreateRoomRsp",
	1205: "MvsLeaveRoomReq",
	1206: "MvsLeaveRoomRsp",
	1209: "MvsGetRoomDetailReq",
	1210: "MvsGetRoomDetailRsp",
	1211: "MvsGetRoomDetailPush",
	1213: "MvsJoinOverReq",
	1214: "MvsJoinOverRsp",
	1219: "MvsSetRoomPropertyReq",
	1220: "MvsSetRoomPropertyRsp",
	1221: "MvsJoinOpenReq",
	1222: "MvsJoinOpenRsp",
	1303: "MvsKickPlayerReq",
	1304: "MvsKickPlayerRsp",
	1120: "MvsNetworkStateReq",
	1121: "MvsNetworkStateRsp",
}

var MvsGsCmdID_value = map[string]int32{
	"MvsCmdNone":            0,
	"MvsJoinRoomReq":        1201,
	"MvsJoinRoomRsp":        1202,
	"MvsCreateRoomReq":      1203,
	"MvsCreateRoomRsp":      1204,
	"MvsLeaveRoomReq":       1205,
	"MvsLeaveRoomRsp":       1206,
	"MvsGetRoomDetailReq":   1209,
	"MvsGetRoomDetailRsp":   1210,
	"MvsGetRoomDetailPush":  1211,
	"MvsJoinOverReq":        1213,
	"MvsJoinOverRsp":        1214,
	"MvsSetRoomPropertyReq": 1219,
	"MvsSetRoomPropertyRsp": 1220,
	"MvsJoinOpenReq":        1221,
	"MvsJoinOpenRsp":        1222,
	"MvsKickPlayerReq":      1303,
	"MvsKickPlayerRsp":      1304,
	"MvsNetworkStateReq":    1120,
	"MvsNetworkStateRsp":    1121,
}

func (x MvsGsCmdID) String() string {
	return proto.EnumName(MvsGsCmdID_name, int32(x))
}

func (MvsGsCmdID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{0}
}

//gs->mvs
type JoinOverReq struct {
	RoomID               uint64   `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	GameID               uint32   `protobuf:"varint,2,opt,name=gameID,proto3" json:"gameID,omitempty"`
	CpProto              []byte   `protobuf:"bytes,3,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	UserID               uint32   `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinOverReq) Reset()         { *m = JoinOverReq{} }
func (m *JoinOverReq) String() string { return proto.CompactTextString(m) }
func (*JoinOverReq) ProtoMessage()    {}
func (*JoinOverReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{0}
}

func (m *JoinOverReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinOverReq.Unmarshal(m, b)
}
func (m *JoinOverReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinOverReq.Marshal(b, m, deterministic)
}
func (m *JoinOverReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinOverReq.Merge(m, src)
}
func (m *JoinOverReq) XXX_Size() int {
	return xxx_messageInfo_JoinOverReq.Size(m)
}
func (m *JoinOverReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinOverReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinOverReq proto.InternalMessageInfo

func (m *JoinOverReq) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *JoinOverReq) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *JoinOverReq) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

func (m *JoinOverReq) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type JoinOverRsp struct {
	Status               ErrorCode `protobuf:"varint,1,opt,name=status,proto3,enum=stream.ErrorCode" json:"status,omitempty"`
	CpProto              []byte    `protobuf:"bytes,2,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinOverRsp) Reset()         { *m = JoinOverRsp{} }
func (m *JoinOverRsp) String() string { return proto.CompactTextString(m) }
func (*JoinOverRsp) ProtoMessage()    {}
func (*JoinOverRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{1}
}

func (m *JoinOverRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinOverRsp.Unmarshal(m, b)
}
func (m *JoinOverRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinOverRsp.Marshal(b, m, deterministic)
}
func (m *JoinOverRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinOverRsp.Merge(m, src)
}
func (m *JoinOverRsp) XXX_Size() int {
	return xxx_messageInfo_JoinOverRsp.Size(m)
}
func (m *JoinOverRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinOverRsp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinOverRsp proto.InternalMessageInfo

func (m *JoinOverRsp) GetStatus() ErrorCode {
	if m != nil {
		return m.Status
	}
	return ErrorCode_NoError
}

func (m *JoinOverRsp) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

type JoinOpenReq struct {
	RoomID               uint64   `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	GameID               uint32   `protobuf:"varint,2,opt,name=gameID,proto3" json:"gameID,omitempty"`
	UserID               uint32   `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	CpProto              []byte   `protobuf:"bytes,4,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinOpenReq) Reset()         { *m = JoinOpenReq{} }
func (m *JoinOpenReq) String() string { return proto.CompactTextString(m) }
func (*JoinOpenReq) ProtoMessage()    {}
func (*JoinOpenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{2}
}

func (m *JoinOpenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinOpenReq.Unmarshal(m, b)
}
func (m *JoinOpenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinOpenReq.Marshal(b, m, deterministic)
}
func (m *JoinOpenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinOpenReq.Merge(m, src)
}
func (m *JoinOpenReq) XXX_Size() int {
	return xxx_messageInfo_JoinOpenReq.Size(m)
}
func (m *JoinOpenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinOpenReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinOpenReq proto.InternalMessageInfo

func (m *JoinOpenReq) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *JoinOpenReq) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *JoinOpenReq) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *JoinOpenReq) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

type JoinOpenRsp struct {
	Status               ErrorCode `protobuf:"varint,1,opt,name=status,proto3,enum=stream.ErrorCode" json:"status,omitempty"`
	CpProto              []byte    `protobuf:"bytes,2,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinOpenRsp) Reset()         { *m = JoinOpenRsp{} }
func (m *JoinOpenRsp) String() string { return proto.CompactTextString(m) }
func (*JoinOpenRsp) ProtoMessage()    {}
func (*JoinOpenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{3}
}

func (m *JoinOpenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinOpenRsp.Unmarshal(m, b)
}
func (m *JoinOpenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinOpenRsp.Marshal(b, m, deterministic)
}
func (m *JoinOpenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinOpenRsp.Merge(m, src)
}
func (m *JoinOpenRsp) XXX_Size() int {
	return xxx_messageInfo_JoinOpenRsp.Size(m)
}
func (m *JoinOpenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinOpenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinOpenRsp proto.InternalMessageInfo

func (m *JoinOpenRsp) GetStatus() ErrorCode {
	if m != nil {
		return m.Status
	}
	return ErrorCode_NoError
}

func (m *JoinOpenRsp) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

//gs->mvs
type KickPlayer struct {
	RoomID               uint64   `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	SrcUserID            uint32   `protobuf:"varint,2,opt,name=srcUserID,proto3" json:"srcUserID,omitempty"`
	UserID               uint32   `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	CpProto              []byte   `protobuf:"bytes,4,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickPlayer) Reset()         { *m = KickPlayer{} }
func (m *KickPlayer) String() string { return proto.CompactTextString(m) }
func (*KickPlayer) ProtoMessage()    {}
func (*KickPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{4}
}

func (m *KickPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickPlayer.Unmarshal(m, b)
}
func (m *KickPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickPlayer.Marshal(b, m, deterministic)
}
func (m *KickPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickPlayer.Merge(m, src)
}
func (m *KickPlayer) XXX_Size() int {
	return xxx_messageInfo_KickPlayer.Size(m)
}
func (m *KickPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_KickPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_KickPlayer proto.InternalMessageInfo

func (m *KickPlayer) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *KickPlayer) GetSrcUserID() uint32 {
	if m != nil {
		return m.SrcUserID
	}
	return 0
}

func (m *KickPlayer) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *KickPlayer) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

type KickPlayerRsp struct {
	Status               ErrorCode `protobuf:"varint,1,opt,name=status,proto3,enum=stream.ErrorCode" json:"status,omitempty"`
	UserID               uint32    `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	RoomID               uint64    `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *KickPlayerRsp) Reset()         { *m = KickPlayerRsp{} }
func (m *KickPlayerRsp) String() string { return proto.CompactTextString(m) }
func (*KickPlayerRsp) ProtoMessage()    {}
func (*KickPlayerRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{5}
}

func (m *KickPlayerRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickPlayerRsp.Unmarshal(m, b)
}
func (m *KickPlayerRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickPlayerRsp.Marshal(b, m, deterministic)
}
func (m *KickPlayerRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickPlayerRsp.Merge(m, src)
}
func (m *KickPlayerRsp) XXX_Size() int {
	return xxx_messageInfo_KickPlayerRsp.Size(m)
}
func (m *KickPlayerRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_KickPlayerRsp.DiscardUnknown(m)
}

var xxx_messageInfo_KickPlayerRsp proto.InternalMessageInfo

func (m *KickPlayerRsp) GetStatus() ErrorCode {
	if m != nil {
		return m.Status
	}
	return ErrorCode_NoError
}

func (m *KickPlayerRsp) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *KickPlayerRsp) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

//mvs->gs
type Request struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	GameID               uint32   `protobuf:"varint,2,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	CpProto              []byte   `protobuf:"bytes,4,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{6}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Request) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *Request) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *Request) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

type Reply struct {
	UserID               uint32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	GameID               uint32    `protobuf:"varint,2,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64    `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	CpProto              []byte    `protobuf:"bytes,4,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	Errno                ErrorCode `protobuf:"varint,5,opt,name=errno,proto3,enum=stream.ErrorCode" json:"errno,omitempty"`
	ErrMsg               string    `protobuf:"bytes,6,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{7}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Reply) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *Reply) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *Reply) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

func (m *Reply) GetErrno() ErrorCode {
	if m != nil {
		return m.Errno
	}
	return ErrorCode_NoError
}

func (m *Reply) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

//gs->mvs
type PushMsg struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	GameID               uint32   `protobuf:"varint,2,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Users                []uint32 `protobuf:"varint,4,rep,packed,name=users,proto3" json:"users,omitempty"`
	CpProto              []byte   `protobuf:"bytes,5,opt,name=cpProto,proto3" json:"cpProto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsg) Reset()         { *m = PushMsg{} }
func (m *PushMsg) String() string { return proto.CompactTextString(m) }
func (*PushMsg) ProtoMessage()    {}
func (*PushMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{8}
}

func (m *PushMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsg.Unmarshal(m, b)
}
func (m *PushMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsg.Marshal(b, m, deterministic)
}
func (m *PushMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsg.Merge(m, src)
}
func (m *PushMsg) XXX_Size() int {
	return xxx_messageInfo_PushMsg.Size(m)
}
func (m *PushMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsg proto.InternalMessageInfo

func (m *PushMsg) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *PushMsg) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *PushMsg) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *PushMsg) GetUsers() []uint32 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *PushMsg) GetCpProto() []byte {
	if m != nil {
		return m.CpProto
	}
	return nil
}

type GetRoomDetailReq struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	LatestWatcherNum     uint32   `protobuf:"varint,3,opt,name=latestWatcherNum,proto3" json:"latestWatcherNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoomDetailReq) Reset()         { *m = GetRoomDetailReq{} }
func (m *GetRoomDetailReq) String() string { return proto.CompactTextString(m) }
func (*GetRoomDetailReq) ProtoMessage()    {}
func (*GetRoomDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{9}
}

func (m *GetRoomDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomDetailReq.Unmarshal(m, b)
}
func (m *GetRoomDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomDetailReq.Marshal(b, m, deterministic)
}
func (m *GetRoomDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomDetailReq.Merge(m, src)
}
func (m *GetRoomDetailReq) XXX_Size() int {
	return xxx_messageInfo_GetRoomDetailReq.Size(m)
}
func (m *GetRoomDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomDetailReq proto.InternalMessageInfo

func (m *GetRoomDetailReq) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *GetRoomDetailReq) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *GetRoomDetailReq) GetLatestWatcherNum() uint32 {
	if m != nil {
		return m.LatestWatcherNum
	}
	return 0
}

type GetRoomDetailRsp struct {
	Status               ErrorCode   `protobuf:"varint,1,opt,name=status,proto3,enum=stream.ErrorCode" json:"status,omitempty"`
	RoomDetail           *RoomDetail `protobuf:"bytes,2,opt,name=roomDetail,proto3" json:"roomDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRoomDetailRsp) Reset()         { *m = GetRoomDetailRsp{} }
func (m *GetRoomDetailRsp) String() string { return proto.CompactTextString(m) }
func (*GetRoomDetailRsp) ProtoMessage()    {}
func (*GetRoomDetailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{10}
}

func (m *GetRoomDetailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomDetailRsp.Unmarshal(m, b)
}
func (m *GetRoomDetailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomDetailRsp.Marshal(b, m, deterministic)
}
func (m *GetRoomDetailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomDetailRsp.Merge(m, src)
}
func (m *GetRoomDetailRsp) XXX_Size() int {
	return xxx_messageInfo_GetRoomDetailRsp.Size(m)
}
func (m *GetRoomDetailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomDetailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomDetailRsp proto.InternalMessageInfo

func (m *GetRoomDetailRsp) GetStatus() ErrorCode {
	if m != nil {
		return m.Status
	}
	return ErrorCode_NoError
}

func (m *GetRoomDetailRsp) GetRoomDetail() *RoomDetail {
	if m != nil {
		return m.RoomDetail
	}
	return nil
}

type RoomDetail struct {
	RoomID               uint64        `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	State                uint32        `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	MaxPlayer            uint32        `protobuf:"varint,3,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	Mode                 int32         `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	CanWatch             int32         `protobuf:"varint,5,opt,name=canWatch,proto3" json:"canWatch,omitempty"`
	RoomProperty         []byte        `protobuf:"bytes,6,opt,name=roomProperty,proto3" json:"roomProperty,omitempty"`
	Owner                uint32        `protobuf:"varint,7,opt,name=owner,proto3" json:"owner,omitempty"`
	CreateFlag           uint32        `protobuf:"varint,8,opt,name=createFlag,proto3" json:"createFlag,omitempty"`
	PlayerInfos          []*PlayerInfo `protobuf:"bytes,9,rep,name=playerInfos,proto3" json:"playerInfos,omitempty"`
	WatchRoom            *WatchRoom    `protobuf:"bytes,10,opt,name=watchRoom,proto3" json:"watchRoom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomDetail) Reset()         { *m = RoomDetail{} }
func (m *RoomDetail) String() string { return proto.CompactTextString(m) }
func (*RoomDetail) ProtoMessage()    {}
func (*RoomDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{11}
}

func (m *RoomDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDetail.Unmarshal(m, b)
}
func (m *RoomDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDetail.Marshal(b, m, deterministic)
}
func (m *RoomDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDetail.Merge(m, src)
}
func (m *RoomDetail) XXX_Size() int {
	return xxx_messageInfo_RoomDetail.Size(m)
}
func (m *RoomDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDetail.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDetail proto.InternalMessageInfo

func (m *RoomDetail) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RoomDetail) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *RoomDetail) GetMaxPlayer() uint32 {
	if m != nil {
		return m.MaxPlayer
	}
	return 0
}

func (m *RoomDetail) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *RoomDetail) GetCanWatch() int32 {
	if m != nil {
		return m.CanWatch
	}
	return 0
}

func (m *RoomDetail) GetRoomProperty() []byte {
	if m != nil {
		return m.RoomProperty
	}
	return nil
}

func (m *RoomDetail) GetOwner() uint32 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *RoomDetail) GetCreateFlag() uint32 {
	if m != nil {
		return m.CreateFlag
	}
	return 0
}

func (m *RoomDetail) GetPlayerInfos() []*PlayerInfo {
	if m != nil {
		return m.PlayerInfos
	}
	return nil
}

func (m *RoomDetail) GetWatchRoom() *WatchRoom {
	if m != nil {
		return m.WatchRoom
	}
	return nil
}

type PlayerInfo struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserProfile          []byte   `protobuf:"bytes,2,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{12}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *PlayerInfo) GetUserProfile() []byte {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type CreateExtInfo struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserProfile          []byte   `protobuf:"bytes,2,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	RoomID               uint64   `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	State                uint32   `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	MaxPlayer            uint32   `protobuf:"varint,5,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	Mode                 int32    `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	CanWatch             int32    `protobuf:"varint,7,opt,name=canWatch,proto3" json:"canWatch,omitempty"`
	RoomProperty         []byte   `protobuf:"bytes,8,opt,name=roomProperty,proto3" json:"roomProperty,omitempty"`
	CreateFlag           uint32   `protobuf:"varint,9,opt,name=createFlag,proto3" json:"createFlag,omitempty"`
	CreateTime           uint64   `protobuf:"varint,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateExtInfo) Reset()         { *m = CreateExtInfo{} }
func (m *CreateExtInfo) String() string { return proto.CompactTextString(m) }
func (*CreateExtInfo) ProtoMessage()    {}
func (*CreateExtInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{13}
}

func (m *CreateExtInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExtInfo.Unmarshal(m, b)
}
func (m *CreateExtInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExtInfo.Marshal(b, m, deterministic)
}
func (m *CreateExtInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExtInfo.Merge(m, src)
}
func (m *CreateExtInfo) XXX_Size() int {
	return xxx_messageInfo_CreateExtInfo.Size(m)
}
func (m *CreateExtInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExtInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExtInfo proto.InternalMessageInfo

func (m *CreateExtInfo) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreateExtInfo) GetUserProfile() []byte {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *CreateExtInfo) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *CreateExtInfo) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *CreateExtInfo) GetMaxPlayer() uint32 {
	if m != nil {
		return m.MaxPlayer
	}
	return 0
}

func (m *CreateExtInfo) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *CreateExtInfo) GetCanWatch() int32 {
	if m != nil {
		return m.CanWatch
	}
	return 0
}

func (m *CreateExtInfo) GetRoomProperty() []byte {
	if m != nil {
		return m.RoomProperty
	}
	return nil
}

func (m *CreateExtInfo) GetCreateFlag() uint32 {
	if m != nil {
		return m.CreateFlag
	}
	return 0
}

func (m *CreateExtInfo) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type JoinExtInfo struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserProfile          []byte   `protobuf:"bytes,2,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	RoomID               uint64   `protobuf:"varint,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	JoinType             uint32   `protobuf:"varint,4,opt,name=JoinType,proto3" json:"JoinType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinExtInfo) Reset()         { *m = JoinExtInfo{} }
func (m *JoinExtInfo) String() string { return proto.CompactTextString(m) }
func (*JoinExtInfo) ProtoMessage()    {}
func (*JoinExtInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{14}
}

func (m *JoinExtInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinExtInfo.Unmarshal(m, b)
}
func (m *JoinExtInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinExtInfo.Marshal(b, m, deterministic)
}
func (m *JoinExtInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinExtInfo.Merge(m, src)
}
func (m *JoinExtInfo) XXX_Size() int {
	return xxx_messageInfo_JoinExtInfo.Size(m)
}
func (m *JoinExtInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinExtInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JoinExtInfo proto.InternalMessageInfo

func (m *JoinExtInfo) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *JoinExtInfo) GetUserProfile() []byte {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *JoinExtInfo) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *JoinExtInfo) GetJoinType() uint32 {
	if m != nil {
		return m.JoinType
	}
	return 0
}

type SetRoomPropertyReq struct {
	GameID               uint32   `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RoomID               uint64   `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	UserID               uint32   `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	RoomProperty         []byte   `protobuf:"bytes,4,opt,name=roomProperty,proto3" json:"roomProperty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRoomPropertyReq) Reset()         { *m = SetRoomPropertyReq{} }
func (m *SetRoomPropertyReq) String() string { return proto.CompactTextString(m) }
func (*SetRoomPropertyReq) ProtoMessage()    {}
func (*SetRoomPropertyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{15}
}

func (m *SetRoomPropertyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRoomPropertyReq.Unmarshal(m, b)
}
func (m *SetRoomPropertyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRoomPropertyReq.Marshal(b, m, deterministic)
}
func (m *SetRoomPropertyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRoomPropertyReq.Merge(m, src)
}
func (m *SetRoomPropertyReq) XXX_Size() int {
	return xxx_messageInfo_SetRoomPropertyReq.Size(m)
}
func (m *SetRoomPropertyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRoomPropertyReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetRoomPropertyReq proto.InternalMessageInfo

func (m *SetRoomPropertyReq) GetGameID() uint32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *SetRoomPropertyReq) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *SetRoomPropertyReq) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SetRoomPropertyReq) GetRoomProperty() []byte {
	if m != nil {
		return m.RoomProperty
	}
	return nil
}

type SetRoomPropertyRsp struct {
	Status               ErrorCode `protobuf:"varint,1,opt,name=status,proto3,enum=stream.ErrorCode" json:"status,omitempty"`
	RoomID               uint64    `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	UserID               uint32    `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	RoomProperty         []byte    `protobuf:"bytes,4,opt,name=roomProperty,proto3" json:"roomProperty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetRoomPropertyRsp) Reset()         { *m = SetRoomPropertyRsp{} }
func (m *SetRoomPropertyRsp) String() string { return proto.CompactTextString(m) }
func (*SetRoomPropertyRsp) ProtoMessage()    {}
func (*SetRoomPropertyRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{16}
}

func (m *SetRoomPropertyRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRoomPropertyRsp.Unmarshal(m, b)
}
func (m *SetRoomPropertyRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRoomPropertyRsp.Marshal(b, m, deterministic)
}
func (m *SetRoomPropertyRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRoomPropertyRsp.Merge(m, src)
}
func (m *SetRoomPropertyRsp) XXX_Size() int {
	return xxx_messageInfo_SetRoomPropertyRsp.Size(m)
}
func (m *SetRoomPropertyRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRoomPropertyRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SetRoomPropertyRsp proto.InternalMessageInfo

func (m *SetRoomPropertyRsp) GetStatus() ErrorCode {
	if m != nil {
		return m.Status
	}
	return ErrorCode_NoError
}

func (m *SetRoomPropertyRsp) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *SetRoomPropertyRsp) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SetRoomPropertyRsp) GetRoomProperty() []byte {
	if m != nil {
		return m.RoomProperty
	}
	return nil
}

// 观战详情
type WatchInfo struct {
	RoomID               uint64        `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	State                uint32        `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	WatchSetting         *WatchSetting `protobuf:"bytes,3,opt,name=watchSetting,proto3" json:"watchSetting,omitempty"`
	CurWatch             uint32        `protobuf:"varint,4,opt,name=curWatch,proto3" json:"curWatch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WatchInfo) Reset()         { *m = WatchInfo{} }
func (m *WatchInfo) String() string { return proto.CompactTextString(m) }
func (*WatchInfo) ProtoMessage()    {}
func (*WatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{17}
}

func (m *WatchInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchInfo.Unmarshal(m, b)
}
func (m *WatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchInfo.Marshal(b, m, deterministic)
}
func (m *WatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchInfo.Merge(m, src)
}
func (m *WatchInfo) XXX_Size() int {
	return xxx_messageInfo_WatchInfo.Size(m)
}
func (m *WatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WatchInfo proto.InternalMessageInfo

func (m *WatchInfo) GetRoomID() uint64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *WatchInfo) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *WatchInfo) GetWatchSetting() *WatchSetting {
	if m != nil {
		return m.WatchSetting
	}
	return nil
}

func (m *WatchInfo) GetCurWatch() uint32 {
	if m != nil {
		return m.CurWatch
	}
	return 0
}

type WatchRoom struct {
	WatchInfo            *WatchInfo    `protobuf:"bytes,1,opt,name=watchInfo,proto3" json:"watchInfo,omitempty"`
	WatchPlayers         []*PlayerInfo `protobuf:"bytes,2,rep,name=watchPlayers,proto3" json:"watchPlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WatchRoom) Reset()         { *m = WatchRoom{} }
func (m *WatchRoom) String() string { return proto.CompactTextString(m) }
func (*WatchRoom) ProtoMessage()    {}
func (*WatchRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_562d1a60f6d3700c, []int{18}
}

func (m *WatchRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchRoom.Unmarshal(m, b)
}
func (m *WatchRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchRoom.Marshal(b, m, deterministic)
}
func (m *WatchRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchRoom.Merge(m, src)
}
func (m *WatchRoom) XXX_Size() int {
	return xxx_messageInfo_WatchRoom.Size(m)
}
func (m *WatchRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchRoom.DiscardUnknown(m)
}

var xxx_messageInfo_WatchRoom proto.InternalMessageInfo

func (m *WatchRoom) GetWatchInfo() *WatchInfo {
	if m != nil {
		return m.WatchInfo
	}
	return nil
}

func (m *WatchRoom) GetWatchPlayers() []*PlayerInfo {
	if m != nil {
		return m.WatchPlayers
	}
	return nil
}

func init() {
	proto.RegisterEnum("stream.MvsGsCmdID", MvsGsCmdID_name, MvsGsCmdID_value)
	proto.RegisterType((*JoinOverReq)(nil), "stream.JoinOverReq")
	proto.RegisterType((*JoinOverRsp)(nil), "stream.JoinOverRsp")
	proto.RegisterType((*JoinOpenReq)(nil), "stream.JoinOpenReq")
	proto.RegisterType((*JoinOpenRsp)(nil), "stream.JoinOpenRsp")
	proto.RegisterType((*KickPlayer)(nil), "stream.KickPlayer")
	proto.RegisterType((*KickPlayerRsp)(nil), "stream.KickPlayerRsp")
	proto.RegisterType((*Request)(nil), "stream.Request")
	proto.RegisterType((*Reply)(nil), "stream.Reply")
	proto.RegisterType((*PushMsg)(nil), "stream.PushMsg")
	proto.RegisterType((*GetRoomDetailReq)(nil), "stream.GetRoomDetailReq")
	proto.RegisterType((*GetRoomDetailRsp)(nil), "stream.GetRoomDetailRsp")
	proto.RegisterType((*RoomDetail)(nil), "stream.RoomDetail")
	proto.RegisterType((*PlayerInfo)(nil), "stream.PlayerInfo")
	proto.RegisterType((*CreateExtInfo)(nil), "stream.CreateExtInfo")
	proto.RegisterType((*JoinExtInfo)(nil), "stream.JoinExtInfo")
	proto.RegisterType((*SetRoomPropertyReq)(nil), "stream.SetRoomPropertyReq")
	proto.RegisterType((*SetRoomPropertyRsp)(nil), "stream.SetRoomPropertyRsp")
	proto.RegisterType((*WatchInfo)(nil), "stream.WatchInfo")
	proto.RegisterType((*WatchRoom)(nil), "stream.WatchRoom")
}

func init() { proto.RegisterFile("gsmvs.proto", fileDescriptor_562d1a60f6d3700c) }

var fileDescriptor_562d1a60f6d3700c = []byte{
	// 961 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x4d, 0x8f, 0x1b, 0x35,
	0x18, 0x66, 0x92, 0x4c, 0x92, 0x79, 0x93, 0xdd, 0x1a, 0x37, 0x85, 0x21, 0x42, 0x55, 0x34, 0x17,
	0x42, 0x0f, 0x0b, 0x5a, 0x10, 0xe2, 0xcc, 0xa6, 0xad, 0x02, 0x64, 0x89, 0xbc, 0x45, 0x3d, 0x0f,
	0x89, 0x9b, 0x86, 0xcd, 0x8c, 0x27, 0xb6, 0x93, 0xed, 0x8a, 0x0b, 0xfc, 0x06, 0x0e, 0xf0, 0x17,
	0xe0, 0xc6, 0xa7, 0x04, 0x08, 0x2e, 0x7c, 0x48, 0xfc, 0x06, 0x2e, 0xf0, 0x4f, 0x90, 0xed, 0x49,
	0xc6, 0x93, 0x64, 0x5a, 0xed, 0xb6, 0x7b, 0xcb, 0xfb, 0x61, 0x3f, 0xcf, 0xfb, 0xe9, 0x09, 0x34,
	0x26, 0x22, 0x5a, 0x8a, 0x83, 0x84, 0x33, 0xc9, 0x70, 0x55, 0x48, 0x4e, 0xc3, 0xa8, 0x7d, 0x8d,
	0x72, 0xce, 0xf8, 0x88, 0x8d, 0xa9, 0x31, 0xb4, 0x9b, 0x23, 0x16, 0x45, 0x2c, 0x36, 0x52, 0xc0,
	0xa0, 0xf1, 0x2e, 0x9b, 0xc6, 0x1f, 0x2c, 0x29, 0x27, 0x74, 0x8e, 0x5f, 0x80, 0x2a, 0x67, 0x2c,
	0xea, 0xf7, 0x7c, 0xa7, 0xe3, 0x74, 0x2b, 0x24, 0x95, 0x94, 0x7e, 0x12, 0x46, 0xb4, 0xdf, 0xf3,
	0x4b, 0x1d, 0xa7, 0xbb, 0x47, 0x52, 0x09, 0xfb, 0x50, 0x1b, 0x25, 0x43, 0x75, 0x93, 0x5f, 0xee,
	0x38, 0xdd, 0x26, 0x59, 0x89, 0xea, 0xc4, 0x42, 0x50, 0xde, 0xef, 0xf9, 0x15, 0x73, 0xc2, 0x48,
	0x01, 0xb1, 0x00, 0x45, 0x82, 0x5f, 0x85, 0xaa, 0x90, 0xa1, 0x5c, 0x08, 0x0d, 0xb8, 0x7f, 0xf8,
	0xfc, 0x81, 0xe1, 0x7d, 0x70, 0x5b, 0xd1, 0x3e, 0x62, 0x63, 0x4a, 0x52, 0x07, 0x1b, 0xab, 0x94,
	0xc3, 0x5a, 0x07, 0x91, 0xd0, 0xf8, 0x32, 0x41, 0x64, 0x54, 0xcb, 0x36, 0x55, 0x1b, 0xb0, 0x92,
	0x07, 0x24, 0x16, 0xe0, 0xb3, 0x0a, 0x42, 0x02, 0xbc, 0x37, 0x1d, 0x9d, 0x0e, 0x67, 0xe1, 0x39,
	0xe5, 0x85, 0x31, 0xbc, 0x0c, 0x9e, 0xe0, 0xa3, 0x0f, 0x0d, 0x5d, 0x13, 0x46, 0xa6, 0xb8, 0x44,
	0x24, 0x1f, 0xc3, 0x5e, 0x86, 0x7a, 0xc1, 0x58, 0x32, 0xb4, 0x52, 0x0e, 0x2d, 0xe3, 0x5e, 0xb6,
	0xb9, 0x07, 0xa7, 0x50, 0x23, 0x74, 0xbe, 0xa0, 0x42, 0x5a, 0x47, 0x9d, 0xcd, 0xa3, 0x45, 0x25,
	0xda, 0x75, 0xe5, 0x63, 0x02, 0xfb, 0xda, 0x01, 0x97, 0xd0, 0x64, 0x76, 0x7e, 0xf5, 0x58, 0xf8,
	0x15, 0x70, 0x29, 0xe7, 0x31, 0xf3, 0xdd, 0xa2, 0x94, 0x19, 0xbb, 0xba, 0x9a, 0x72, 0x3e, 0x10,
	0x13, 0xbf, 0xda, 0x71, 0xba, 0x1e, 0x49, 0xa5, 0xe0, 0x33, 0x07, 0x6a, 0xc3, 0x85, 0x78, 0x38,
	0x10, 0x93, 0x67, 0x46, 0xb7, 0x05, 0xae, 0x3a, 0x29, 0xfc, 0x4a, 0xa7, 0xdc, 0xdd, 0x23, 0x46,
	0xb0, 0x83, 0x70, 0xf3, 0x09, 0x8b, 0x01, 0xdd, 0xa5, 0x92, 0x30, 0x16, 0xf5, 0xa8, 0x0c, 0xa7,
	0xb3, 0x74, 0x92, 0x52, 0x4c, 0xa7, 0x00, 0xb3, 0x94, 0xc3, 0xbc, 0x05, 0x68, 0x16, 0x4a, 0x2a,
	0xe4, 0xfd, 0x50, 0x8e, 0x1e, 0x52, 0x7e, 0xbc, 0x88, 0xd2, 0x4e, 0xdc, 0xd2, 0x07, 0xf3, 0x4d,
	0xbc, 0x8b, 0x35, 0xdf, 0x21, 0x00, 0x5f, 0x9f, 0xd5, 0x34, 0x1a, 0x87, 0x78, 0xe5, 0x6e, 0xdd,
	0x6a, 0x79, 0x05, 0x7f, 0x97, 0x00, 0x32, 0x53, 0xe1, 0x8c, 0xb5, 0xc0, 0x55, 0x20, 0x34, 0x4d,
	0xb4, 0x11, 0xd4, 0xe4, 0x45, 0xe1, 0x23, 0x33, 0x28, 0x69, 0x50, 0x99, 0x02, 0x63, 0xa8, 0x44,
	0x6c, 0x4c, 0x75, 0x67, 0xb8, 0x44, 0xff, 0xc6, 0x6d, 0xa8, 0x8f, 0xc2, 0x58, 0x87, 0xac, 0x93,
	0xed, 0x92, 0xb5, 0x8c, 0x03, 0x68, 0x2a, 0xb4, 0x21, 0x67, 0x09, 0xe5, 0xf2, 0x5c, 0xf7, 0x43,
	0x93, 0xe4, 0x74, 0x8a, 0x07, 0x3b, 0x8b, 0x29, 0xf7, 0x6b, 0x86, 0x87, 0x16, 0xf0, 0x4d, 0x80,
	0x11, 0xa7, 0xa1, 0xa4, 0x77, 0x66, 0xe1, 0xc4, 0xaf, 0x6b, 0x93, 0xa5, 0xc1, 0x6f, 0x42, 0x23,
	0xd1, 0x9c, 0xfa, 0xf1, 0x03, 0x26, 0x7c, 0xaf, 0x53, 0xb6, 0x33, 0x33, 0x5c, 0x9b, 0x88, 0xed,
	0x86, 0x5f, 0x03, 0xef, 0x4c, 0x11, 0x53, 0xe9, 0xf1, 0x41, 0x67, 0x73, 0x9d, 0xfc, 0xfb, 0x2b,
	0x03, 0xc9, 0x7c, 0x82, 0x3b, 0x00, 0xd9, 0x5d, 0x85, 0x4d, 0xdb, 0x81, 0x86, 0xfa, 0x35, 0xe4,
	0xec, 0xc1, 0x74, 0x46, 0xd3, 0x95, 0x67, 0xab, 0x82, 0xaf, 0x4a, 0xb0, 0x77, 0xa4, 0xd9, 0xdf,
	0x7e, 0x24, 0x9f, 0xee, 0xae, 0xc7, 0x8d, 0x82, 0x29, 0x68, 0xa5, 0xb0, 0xa0, 0x6e, 0x51, 0x41,
	0xab, 0x05, 0x05, 0xad, 0x3d, 0xa1, 0xa0, 0xf5, 0x1d, 0x05, 0xcd, 0x97, 0xce, 0xdb, 0x2a, 0xdd,
	0x4d, 0x00, 0x93, 0x8a, 0x7b, 0xd3, 0x88, 0xea, 0x2a, 0x54, 0x88, 0xa5, 0x09, 0x3e, 0x31, 0xcf,
	0xce, 0xd5, 0x25, 0xaa, 0x0d, 0x75, 0x05, 0x70, 0xef, 0x3c, 0x59, 0xe5, 0x6a, 0x2d, 0x07, 0x9f,
	0x3a, 0x80, 0x4f, 0xcc, 0xc0, 0xae, 0x02, 0xba, 0xcc, 0x8a, 0x28, 0x7a, 0xa2, 0x36, 0xf3, 0x57,
	0xd9, 0xce, 0x5f, 0xf0, 0xf9, 0x0e, 0x0a, 0x17, 0x7e, 0xb2, 0xae, 0x82, 0x95, 0xa7, 0x7b, 0x40,
	0x17, 0xa5, 0x9d, 0x5f, 0x2a, 0xef, 0x94, 0x5e, 0x77, 0x9e, 0xb0, 0x58, 0xde, 0x86, 0xa6, 0x1e,
	0xab, 0x13, 0x2a, 0xe5, 0x34, 0x9e, 0x68, 0x06, 0x8d, 0xc3, 0x56, 0x6e, 0xfa, 0x52, 0x1b, 0xc9,
	0x79, 0xea, 0x7e, 0x5c, 0x70, 0xd3, 0x8f, 0x69, 0xb9, 0x56, 0x72, 0x20, 0x53, 0x52, 0x2a, 0x59,
	0xeb, 0xe9, 0x56, 0x0c, 0x35, 0xaf, 0xcd, 0xe9, 0xd6, 0x0b, 0x21, 0xf3, 0xc1, 0x6f, 0xa5, 0x9c,
	0xcc, 0x30, 0x08, 0xbf, 0x54, 0xb8, 0x45, 0x72, 0x7e, 0xb7, 0xfe, 0x29, 0x03, 0x0c, 0x96, 0xe2,
	0xae, 0x38, 0x8a, 0xc6, 0xfd, 0x1e, 0xde, 0xd7, 0xd2, 0x51, 0x34, 0x3e, 0x66, 0x31, 0x45, 0xcf,
	0xe1, 0xeb, 0xb0, 0x3f, 0x58, 0x0a, 0xd5, 0x52, 0x7a, 0x9d, 0xd0, 0x39, 0xfa, 0xc6, 0xdb, 0x54,
	0x8a, 0x04, 0x7d, 0xeb, 0xe1, 0x1b, 0x80, 0xd4, 0x49, 0xdd, 0xfb, 0x2b, 0xdf, 0xef, 0x76, 0xa8,
	0x45, 0x82, 0xbe, 0xf7, 0x70, 0x0b, 0xae, 0x0d, 0x96, 0xe2, 0x7d, 0x1a, 0x2e, 0xd7, 0xce, 0x3f,
	0x6c, 0x6b, 0x45, 0x82, 0x7e, 0xf4, 0xb0, 0x0f, 0xd7, 0x15, 0xc3, 0x8d, 0xa7, 0x0e, 0xfd, 0xb4,
	0xdb, 0x22, 0x12, 0xf4, 0xb3, 0x87, 0x5f, 0x82, 0xd6, 0xa6, 0x45, 0x3d, 0xd7, 0xe8, 0x17, 0x9b,
	0x7d, 0xfa, 0x0d, 0x8d, 0x7e, 0xdd, 0x52, 0x8a, 0x04, 0xfd, 0xe6, 0xe1, 0x36, 0xdc, 0x18, 0x2c,
	0xc5, 0xf6, 0x08, 0xa1, 0xdf, 0x8b, 0x6c, 0x22, 0x41, 0x7f, 0xe4, 0x2e, 0x33, 0x1f, 0xb8, 0xe8,
	0xcf, 0x2d, 0xa5, 0x48, 0xd0, 0x5f, 0xab, 0xec, 0x58, 0xdf, 0x73, 0x74, 0x8e, 0xbe, 0x80, 0x6d,
	0xb5, 0x48, 0xd0, 0x97, 0x80, 0x5f, 0x04, 0x3c, 0x58, 0x8a, 0x63, 0x2a, 0xcf, 0x18, 0x3f, 0x3d,
	0x51, 0xad, 0xa8, 0xfc, 0xff, 0xad, 0xef, 0x32, 0x88, 0x04, 0xfd, 0x57, 0xff, 0xa8, 0xaa, 0xff,
	0x33, 0xbc, 0xf1, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0x3c, 0x87, 0x76, 0x69, 0x0c, 0x00,
	0x00,
}
